---
title: "Capstone Project - Wikipedia Network Analysis"
output: html_document
date: "2024-08-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries}
library(readr)
library(igraph)
library(pacman)
p_load('WikipediR', 'rvest', 'xml2')
library(dplyr)
library(ggplot2)
library("httr")
library(tidyverse)
library(knitr)
library(kableExtra)
library(netseg)
set.seed(42)
```

```{r get_pages}
# Prepare function which extracts subcategories
extract_categories <- function(category_string, depth) {
  if (depth > 30) return(NA) # Up to 30 levels of subcategories
  
  # Get the subcateogries of current category
  subcats <- pages_in_category(
    "en", "wikipedia", categories = category_string, type = "subcat")
  
  num_cats <- length(
    subcats$query$categorymembers) # Get number of subcategories from JSON response
  
  # Return NA if no subcategories found
  if (num_cats == 0) return(NA)
  
  cats <- c()
  
  # Iterate through each category member
  for (i in 1:num_cats) {
    cat_title <- subcats$query$categorymembers[[i]]$title
    cats <- c(cats, cat_title)  # Add current category title
  }
  
  # Extract subcategories for all current subcategories (Recursive call)
  for (i in 1:num_cats) {
    # Preprocess category titles:
    current_title <- subcats$query$categorymembers[[i]]$title
    current_title <- gsub("^Category:", "", current_title)
    depth <- depth + 1
    sub_sub_cats <- extract_categories(current_title, depth)
    cats <- c(cats, sub_sub_cats)  # Append extracted sub-subcategories
  }
  
  Sys.sleep(1)
  
  return(cats)
}

# Extract subcategories for the democratic categories
demo_subcats1 <- extract_categories("Democratic Party (United States)", depth = 0)

demo_subcats2 <- extract_categories("Democrats (United States)", depth = 0)

# Combine the two lists
demo_subcats <- union(demo_subcats1, demo_subcats2)

demo_subcats <- gsub(
  "^Category:", "", demo_subcats) # Preprocess category titles

demo_subcats <- demo_subcats[!is.na(demo_subcats)] # remove NA values

# Write to txt file
write.table(demo_subcats, "demo_subcats.txt", row.names = FALSE, col.names = FALSE)

# Same with the republican pages
repub_subcats1 <- extract_categories("Republican Party (United States)", depth = 0)

repub_subcats2 <- extract_categories("Republicans (United States)", depth = 0)

repub_subcats <- union(repub_subcats1, repub_subcats2)

repub_subcats <- gsub("^Category:", "", repub_subcats)

repub_subcats <- repub_subcats[!is.na(repub_subcats)]

write.table(repub_subcats, "repub_subcats.txt", row.names = FALSE, col.names = FALSE)

# Read the cleaned subcategories from the txt files
demo_subcats_delete <- read.table("demo_subcats_delete.txt", header = FALSE, colClasses = "character")
repub_subcats_delete <- read.table("repub_subcats_delete.txt", header = FALSE, colClasses = "character")

# Delete the subcategories that are not relevant
demo_subcats <- demo_subcats[!demo_subcats %in% demo_subcats_delete$V1]
repub_subcats <- repub_subcats[!repub_subcats %in% repub_subcats_delete$V1]

# Prepare function to extract pages from subcategories
extract_pages <- function(subcategory_list) {
  
  pages <- c()
  
  for (i in 1:length(subcategory_list)) {
    # Extract pages for current subcategory
    current_pages <- pages_in_category("en", "wikipedia", categories = subcategory_list[i], type = "page")
    current_num <- length(current_pages$query$categorymembers)
    
    if (current_num == 0) {
      next # If no pages found, continue with next subcategory
    }
    current_titles <- c()
    
    for (j in 1:current_num) {
      # Extract page names from JSON response:
      current_titles[j] <- current_pages$query$categorymembers[[j]]$title
    }
    pages <- c(pages, current_titles) 
  }
  
  Sys.sleep(1)
  
  return(pages)
}

# Extract pages from the democratic subcategories
democrat_pages <- extract_pages(demo_subcats)

democrat_pages <- unique(democrat_pages) # remove duplicates

# Get pages from initial categories
dem_titles <- extract_pages(c("Democratic Party (United States)", "Democrats (United States)"))

missing_pages <- setdiff(dem_titles, democrat_pages) # get pages from original categories

democrat_pages <- c(democrat_pages, missing_pages) # add missing pages

# Repeat for republican pages
republican_pages <- extract_pages(repub_subcats)
republican_pages <- unique(republican_pages)
repub_titles <- extract_pages(c("Republican Party (United States)", "Republicans (United States)"))
missing_pages <- setdiff(repub_titles, republican_pages)
republican_pages <- c(republican_pages, missing_pages)

# Clean and preprocess the titles
republican_pages <- gsub(" ", "_", republican_pages)
clean_repub_titles <- tolower(republican_pages)
democrat_pages <- gsub(" ", "_", democrat_pages)
clean_dem_titles <- tolower(democrat_pages)
clean_repub_titles <- trimws(clean_repub_titles)
clean_dem_titles <- trimws(clean_dem_titles)

# Check which elements appear in both lists
common_pages <- intersect(clean_repub_titles, clean_dem_titles)

# Save to csv
write.csv(common_pages, "common_pages.csv", row.names = FALSE)
```

```{r process_data}
# Define function to process tsv files to igraph objects
process_data_to_graph <- function(file_path, min_weight = 10) {
  # Read the data from the specified file
  data <- read_tsv(file_path, col_names = FALSE, col_select = c(1, 2, 4))
  
  # Remove rows where X4 (the weight column) is less than the specified minimum weight
  data <- data[data$X4 >= min_weight, ]
  
  # Rename the X4 column to "weight"
  colnames(data)[3] <- "weight"
  
  # Create a graph from the data frame
  graph <- graph_from_data_frame(data, directed = TRUE)
  
  # Remove the data frame from memory
  remove(data)
  
  # Return the graph object
  return(graph)
}

# Process 25 networks
net_clicknov19 <- process_data_to_graph("data/clicknov19.tsv")
net_clickdec19 <- process_data_to_graph("data/clickdec19.tsv")
net_clickjan20 <- process_data_to_graph("data/clickjan20.tsv")
net_clickfeb20 <- process_data_to_graph("data/clickfeb20.tsv")
net_clickmar20 <- process_data_to_graph("data/clickmar20.tsv")
net_clickapr20 <- process_data_to_graph("data/clickapr20.tsv")
net_clickmay20 <- process_data_to_graph("data/clickmay20.tsv")
net_clickjun20 <- process_data_to_graph("data/clickjun20.tsv")
net_clickjul20 <- process_data_to_graph("data/clickjul20.tsv")
net_clickaug20 <- process_data_to_graph("data/clickaug20.tsv")
net_clicksep20 <- process_data_to_graph("data/clicksep20.tsv")
net_clickoct20 <- process_data_to_graph("data/clickoct20.tsv")
net_clicknov20 <- process_data_to_graph("data/clicknov20.tsv")
net_clickdec20 <- process_data_to_graph("data/clickdec20.tsv")
net_clickjan21 <- process_data_to_graph("data/clickjan21.tsv")
net_clickfeb21 <- process_data_to_graph("data/clickfeb21.tsv")
net_clickmar21 <- process_data_to_graph("data/clickmar21.tsv")
net_clickapr21 <- process_data_to_graph("data/clickapr21.tsv")
net_clickmay21 <- process_data_to_graph("data/clickmay21.tsv")
net_clickjun21 <- process_data_to_graph("data/clickjun21.tsv")
net_clickjul21 <- process_data_to_graph("data/clickjul21.tsv")
net_clickaug21 <- process_data_to_graph("data/clickaug21.tsv")
net_clicksep21 <- process_data_to_graph("data/clicksep21.tsv")
net_clickoct21 <- process_data_to_graph("data/clickoct21.tsv")
net_clicknov21 <- process_data_to_graph("data/clicknov21.tsv")
```

```{r assign_affiliations}
# Define function to assign party affiliations to nodes
assign_party_affiliation <- function(graph, clean_repub_titles, clean_dem_titles) {
  # Convert vertex names to lowercase, replace spaces with underscores, and trim whitespace
  vertex_names <- tolower(V(graph)$name)
  vertex_names <- gsub(" ", "_", vertex_names)
  vertex_names <- trimws(vertex_names)
  
  # Update vertex names in the graph
  V(graph)$name <- vertex_names
  
  # Get indices of republican and democrat pages
  republican_pages <- which(vertex_names %in% clean_repub_titles)
  democrat_pages <- which(vertex_names %in% clean_dem_titles)
  
  # Initialise party affiliation vector
  party_affiliation <- rep("Other", vcount(graph))
  
  # Assign party affiliations
  party_affiliation[republican_pages] <- "Republican"
  party_affiliation[democrat_pages] <- "Democrat"
  
  # Add the party affiliation attribute to the network
  V(graph)$party <- party_affiliation
  
  # Return the updated graph
  return(graph)
}

# Assign party affiliations for all networks
net_clicknov19 <- assign_party_affiliation(net_clicknov19, clean_repub_titles, clean_dem_titles)
net_clickdec19 <- assign_party_affiliation(net_clickdec19, clean_repub_titles, clean_dem_titles)
net_clickjan20 <- assign_party_affiliation(net_clickjan20, clean_repub_titles, clean_dem_titles)
net_clickfeb20 <- assign_party_affiliation(net_clickfeb20, clean_repub_titles, clean_dem_titles)
net_clickmar20 <- assign_party_affiliation(net_clickmar20, clean_repub_titles, clean_dem_titles)
net_clickapr20 <- assign_party_affiliation(net_clickapr20, clean_repub_titles, clean_dem_titles)
net_clickmay20 <- assign_party_affiliation(net_clickmay20, clean_repub_titles, clean_dem_titles)
net_clickjun20 <- assign_party_affiliation(net_clickjun20, clean_repub_titles, clean_dem_titles)
net_clickjul20 <- assign_party_affiliation(net_clickjul20, clean_repub_titles, clean_dem_titles)
net_clickaug20 <- assign_party_affiliation(net_clickaug20, clean_repub_titles, clean_dem_titles)
net_clicksep20 <- assign_party_affiliation(net_clicksep20, clean_repub_titles, clean_dem_titles)
net_clickoct20 <- assign_party_affiliation(net_clickoct20, clean_repub_titles, clean_dem_titles)
net_clicknov20 <- assign_party_affiliation(net_clicknov20, clean_repub_titles, clean_dem_titles)
net_clickdec20 <- assign_party_affiliation(net_clickdec20, clean_repub_titles, clean_dem_titles)
net_clickjan21 <- assign_party_affiliation(net_clickjan21, clean_repub_titles, clean_dem_titles)
net_clickfeb21 <- assign_party_affiliation(net_clickfeb21, clean_repub_titles, clean_dem_titles)
net_clickmar21 <- assign_party_affiliation(net_clickmar21, clean_repub_titles, clean_dem_titles)
net_clickapr21 <- assign_party_affiliation(net_clickapr21, clean_repub_titles, clean_dem_titles)
net_clickmay21 <- assign_party_affiliation(net_clickmay21, clean_repub_titles, clean_dem_titles)
net_clickjun21 <- assign_party_affiliation(net_clickjun21, clean_repub_titles, clean_dem_titles)
net_clickjul21 <- assign_party_affiliation(net_clickjul21, clean_repub_titles, clean_dem_titles)
net_clickaug21 <- assign_party_affiliation(net_clickaug21, clean_repub_titles, clean_dem_titles)
net_clicksep21 <- assign_party_affiliation(net_clicksep21, clean_repub_titles, clean_dem_titles)
net_clickoct21 <- assign_party_affiliation(net_clickoct21, clean_repub_titles, clean_dem_titles)
net_clicknov21 <- assign_party_affiliation(net_clicknov21, clean_repub_titles, clean_dem_titles)
```

```{r clean_graph}
# Define function that removes isolates and nodes
# which are not connected to Republican or Democrat pages
clean_graph <- function(graph) {
  # Find vertices with party attribute "Republican" or "Democrat"
  rep_dem_vertices <- V(graph)[party %in% c("Republican", "Democrat")]

  neighbors_rep_dem <- integer(0)

  # Iterate through each vertex in rep_dem_vertices
  for (vertex_id in rep_dem_vertices) {
    # Get neighbors of the current vertex
    vertex_neighbors <- neighbors(graph, vertex_id)
    
    # Add neighbors to neighbors_rep_dem
    neighbors_rep_dem <- union(neighbors_rep_dem, vertex_neighbors)
  }

  # Remove duplicates from neighbors_rep_dem
  neighbors_rep_dem <- unique(neighbors_rep_dem)

  neighbors_rep_dem <- V(graph)[neighbors_rep_dem]

  # Combine Republican/Democrat vertices and their neighbors
  vertices_to_keep <- union(rep_dem_vertices, neighbors_rep_dem)

  # Identify vertices not in vertices_to_keep
  vertices_to_delete <- V(graph)[!V(graph) %in% vertices_to_keep]

  # Delete vertices
  cleaned_graph <- delete_vertices(graph, vertices_to_delete)

  # Remove isolates
  cleaned_graph <- delete_vertices(
    cleaned_graph, which(degree(cleaned_graph) == 0))

  # Remove the old non-cleaned graph from memory
  remove(graph)

  # Return the cleaned graph
  return(cleaned_graph)
}

# clean all the networks
net_clicknov19 <- clean_graph(net_clicknov19)
net_clickdec19 <- clean_graph(net_clickdec19)
net_clickjan20 <- clean_graph(net_clickjan20)
net_clickfeb20 <- clean_graph(net_clickfeb20)
net_clickmar20 <- clean_graph(net_clickmar20)
net_clickapr20 <- clean_graph(net_clickapr20)
net_clickmay20 <- clean_graph(net_clickmay20)
net_clickjun20 <- clean_graph(net_clickjun20)
net_clickjul20 <- clean_graph(net_clickjul20)
net_clickaug20 <- clean_graph(net_clickaug20)
net_clicksep20 <- clean_graph(net_clicksep20)
net_clickoct20 <- clean_graph(net_clickoct20)
net_clicknov20 <- clean_graph(net_clicknov20)
net_clickdec20 <- clean_graph(net_clickdec20)
net_clickjan21 <- clean_graph(net_clickjan21)
net_clickfeb21 <- clean_graph(net_clickfeb21)
net_clickmar21 <- clean_graph(net_clickmar21)
net_clickapr21 <- clean_graph(net_clickapr21)
net_clickmay21 <- clean_graph(net_clickmay21)
net_clickjun21 <- clean_graph(net_clickjun21)
net_clickjul21 <- clean_graph(net_clickjul21)
net_clickaug21 <- clean_graph(net_clickaug21)
net_clicksep21 <- clean_graph(net_clicksep21)
net_clickoct21 <- clean_graph(net_clickoct21)
net_clicknov21 <- clean_graph(net_clicknov21)
```

```{r extract_neighbors}
# Get all neighbors of the republican and democrat nodes
extract_neighbors <- function(graph) {
  # Find vertices with party attribute "Republican" or "Democrat"
  rep_dem_vertices <- V(graph)[party %in% c("Republican", "Democrat")]

  neighbors_rep_dem <- integer(0)

  # Iterate through each vertex in rep_dem_vertices
  for (vertex in rep_dem_vertices) {
    # Get neighbors of the current vertex
    vertex_neighbors <- neighbors(graph, vertex, mode = "out")
    
    # Add neighbors to neighbors_rep_dem
    neighbors_rep_dem <- union(neighbors_rep_dem, vertex_neighbors)
  }

  # Remove duplicates from neighbors_rep_dem
  neighbors_rep_dem <- unique(neighbors_rep_dem)

  neighbors_rep_dem <- V(graph)[neighbors_rep_dem]
  
  # get the vertex names
  
  neighbors_rep_dem <- neighbors_rep_dem$name

  return(neighbors_rep_dem)
}
```

```{r update_affiliations}
# Define function that updates affiliations based on
# manual reclassification of pages
update_graph_with_affiliations <- function(graph) {
  
  # Read the neighbor affiliations from the specified file
  affiliations <- read_csv("common_pages.csv", col_names = TRUE)
  
  # Clean the 'Element' column by removing leading and trailing double quotes
  affiliations <- affiliations %>%
    mutate(Element = gsub('^"|"$', '', Element))
  
  # Update the graph with the neighbor affiliations
  for(i in 1:nrow(affiliations)) {
    element <- affiliations$Element[i]
    category <- affiliations$Category[i]
    
    # Find the corresponding node in the graph and update the "party" attribute
    node_index <- which(V(graph)$name == element)
    
    if (length(node_index) > 0) {
      V(graph)$party[node_index] <- category
    }
  }
  
  # Remove the neighbor affiliations data frame from memory
  remove(affiliations)
  
  # Return the updated graph
  return(graph)
}

net_clicknov19 <- update_graph_with_affiliations(net_clicknov19)
net_clickdec19 <- update_graph_with_affiliations(net_clickdec19)
net_clickjan20 <- update_graph_with_affiliations(net_clickjan20)
net_clickfeb20 <- update_graph_with_affiliations(net_clickfeb20)
net_clickmar20 <- update_graph_with_affiliations(net_clickmar20)
net_clickapr20 <- update_graph_with_affiliations(net_clickapr20)
net_clickmay20 <- update_graph_with_affiliations(net_clickmay20)
net_clickjun20 <- update_graph_with_affiliations(net_clickjun20)
net_clickjul20 <- update_graph_with_affiliations(net_clickjul20)
net_clickaug20 <- update_graph_with_affiliations(net_clickaug20)
net_clicksep20 <- update_graph_with_affiliations(net_clicksep20)
net_clickoct20 <- update_graph_with_affiliations(net_clickoct20)
net_clicknov20 <- update_graph_with_affiliations(net_clicknov20)
net_clickdec20 <- update_graph_with_affiliations(net_clickdec20)
net_clickjan21 <- update_graph_with_affiliations(net_clickjan21)
net_clickfeb21 <- update_graph_with_affiliations(net_clickfeb21)
net_clickmar21 <- update_graph_with_affiliations(net_clickmar21)
net_clickapr21 <- update_graph_with_affiliations(net_clickapr21)
net_clickmay21 <- update_graph_with_affiliations(net_clickmay21)
net_clickjun21 <- update_graph_with_affiliations(net_clickjun21)
net_clickjul21 <- update_graph_with_affiliations(net_clickjul21)
net_clickaug21 <- update_graph_with_affiliations(net_clickaug21)
net_clicksep21 <- update_graph_with_affiliations(net_clicksep21)
net_clickoct21 <- update_graph_with_affiliations(net_clickoct21)
net_clicknov21 <- update_graph_with_affiliations(net_clicknov21)
```

```{r descriptive_analysis}
# Define function that counts the number of pages
# for each party classification
analyze_graph <- function(graph) {
  
  # Count the number of vertices with each party affiliation
  num_republican <- sum(V(graph)$party == "Republican")
  num_democrat <- sum(V(graph)$party == "Democrat")
  num_other <- sum(V(graph)$party == "Other")
  
  # Convert party attribute to numeric
  V(graph)$party_num <- as.numeric(factor(V(graph)$party, levels = c("Democrat", "Republican", "Other")))
  
  # Return the results as a list
  return(list(
    num_republican = num_republican,
    num_democrat = num_democrat,
    num_other = num_other
  ))
}

analyse_nov19 <- analyze_graph(net_clicknov19)
analyse_dec19 <- analyze_graph(net_clickdec19)
analyse_jan20 <- analyze_graph(net_clickjan20)
analyse_feb20 <- analyze_graph(net_clickfeb20)
analyse_mar20 <- analyze_graph(net_clickmar20)
analyse_apr20 <- analyze_graph(net_clickapr20)
analyse_may20 <- analyze_graph(net_clickmay20)
analyse_jun20 <- analyze_graph(net_clickjun20)
analyse_jul20 <- analyze_graph(net_clickjul20)
analyse_aug20 <- analyze_graph(net_clickaug20)
analyse_sep20 <- analyze_graph(net_clicksep20)
analyse_oct20 <- analyze_graph(net_clickoct20)
analyse_nov20 <- analyze_graph(net_clicknov20)
analyse_dec20 <- analyze_graph(net_clickdec20)
analyse_jan21 <- analyze_graph(net_clickjan21)
analyse_feb21 <- analyze_graph(net_clickfeb21)
analyse_mar21 <- analyze_graph(net_clickmar21)
analyse_apr21 <- analyze_graph(net_clickapr21)
analyse_may21 <- analyze_graph(net_clickmay21)
analyse_jun21 <- analyze_graph(net_clickjun21)
analyse_jul21 <- analyze_graph(net_clickjul21)
analyse_aug21 <- analyze_graph(net_clickaug21)
analyse_sep21 <- analyze_graph(net_clicksep21)
analyse_oct21 <- analyze_graph(net_clickoct21)
analyse_nov21 <- analyze_graph(net_clicknov21)
```

```{r number_of_pages}
# Create data frames for each category
results <- list(analyse_nov19,analyse_dec19, analyse_jan20, analyse_feb20, analyse_mar20, analyse_apr20, analyse_may20, analyse_jun20, analyse_jul20, analyse_aug20, analyse_sep20, analyse_oct20, analyse_nov20, analyse_dec20, analyse_jan21, analyse_feb21, analyse_mar21, analyse_apr21, analyse_may21, analyse_jun21, analyse_jul21, analyse_aug21, analyse_sep21, analyse_oct21, analyse_nov21
)

# Define the months
months <- c("November 2019", "December 2019", "January 2020", "February 2020", "March 2020", "April 2020", 
            "May 2020", "June 2020", "July 2020", "August 2020", "September 2020", "October 2020", 
            "November 2020", "December 2020", "January 2021", "February 2021", "March 2021", "April 2021", 
            "May 2021", "June 2021", "July 2021", "August 2021", "September 2021", "October 2021", "November 2021")

total_pages <- data.frame(
  Month = months,
  TotalRepPages = sapply(results, function(res) {
    res$num_republican
  }),
  TotalDemPages = sapply(results, function(res) {
    res$num_democrat
  }), 
  TotalOtherPages = sapply(results, function(res) {
    res$num_other
  })
)
```

```{r filter_networks}
# Remove vertices with other party affiliation from all networks
net_clicknov19_filtered <- delete_vertices(
  net_clicknov19, which(V(net_clicknov19)$party == "Other"))

net_clickdec19_filtered <- delete_vertices(
  net_clickdec19, which(V(net_clickdec19)$party == "Other"))

net_clickjan20_filtered <- delete_vertices(
  net_clickjan20, which(V(net_clickjan20)$party == "Other"))

net_clickfeb20_filtered <- delete_vertices(
  net_clickfeb20, which(V(net_clickfeb20)$party == "Other"))

net_clickmar20_filtered <- delete_vertices(
  net_clickmar20, which(V(net_clickmar20)$party == "Other"))

net_clickapr20_filtered <- delete_vertices(
  net_clickapr20, which(V(net_clickapr20)$party == "Other"))

net_clickmay20_filtered <- delete_vertices(
  net_clickmay20, which(V(net_clickmay20)$party == "Other"))

net_clickjun20_filtered <- delete_vertices(
  net_clickjun20, which(V(net_clickjun20)$party == "Other"))

net_clickjul20_filtered <- delete_vertices(
  net_clickjul20, which(V(net_clickjul20)$party == "Other"))

net_clickaug20_filtered <- delete_vertices(
  net_clickaug20, which(V(net_clickaug20)$party == "Other"))

# remove other or politics
net_clicksep20_filtered <- delete_vertices(
  net_clicksep20, which(V(net_clicksep20)$party == "Other"))

net_clicknov20_filtered <- delete_vertices(
  net_clicknov20, which(V(net_clicknov20)$party == "Other"))

net_clickoct20_filtered <- delete_vertices(
  net_clickoct20, which(V(net_clickoct20)$party == "Other"))

net_clickdec20_filtered <- delete_vertices(
  net_clickdec20, which(V(net_clickdec20)$party == "Other"))

net_clickjan21_filtered <- delete_vertices(
  net_clickjan21, which(V(net_clickjan21)$party == "Other"))

net_clickfeb21_filtered <- delete_vertices(
  net_clickfeb21, which(V(net_clickfeb21)$party == "Other"))

net_clickmar21_filtered <- delete_vertices(
  net_clickmar21, which(V(net_clickmar21)$party == "Other"))

net_clickapr21_filtered <- delete_vertices(
  net_clickapr21, which(V(net_clickapr21)$party == "Other"))

net_clickmay21_filtered <- delete_vertices(
  net_clickmay21, which(V(net_clickmay21)$party == "Other"))

net_clickjun21_filtered <- delete_vertices(
  net_clickjun21, which(V(net_clickjun21)$party == "Other"))

net_clickjul21_filtered <- delete_vertices(
  net_clickjul21, which(V(net_clickjul21)$party == "Other"))

net_clickaug21_filtered <- delete_vertices(
  net_clickaug21, which(V(net_clickaug21)$party == "Other"))

net_clicksep21_filtered <- delete_vertices(
  net_clicksep21, which(V(net_clicksep21)$party == "Other"))

net_clickoct21_filtered <- delete_vertices(
  net_clickoct21, which(V(net_clickoct21)$party == "Other"))

net_clicknov21_filtered <- delete_vertices(
  net_clicknov21, which(V(net_clicknov21)$party == "Other"))
```

```{r number_of_edges}
# Create mixing matrices for all months
mixing_matrix_nov19 <- mixingm(net_clicknov19_filtered, "party")
mixing_matrix_dec19 <- mixingm(net_clickdec19_filtered, "party")
mixing_matrix_jan20 <- mixingm(net_clickjan20_filtered, "party")
mixing_matrix_feb20 <- mixingm(net_clickfeb20_filtered, "party")
mixing_matrix_mar20 <- mixingm(net_clickmar20_filtered, "party")
mixing_matrix_apr20 <- mixingm(net_clickapr20_filtered, "party")
mixing_matrix_may20 <- mixingm(net_clickmay20_filtered, "party")
mixing_matrix_jun20 <- mixingm(net_clickjun20_filtered, "party")
mixing_matrix_jul20 <- mixingm(net_clickjul20_filtered, "party")
mixing_matrix_aug20 <- mixingm(net_clickaug20_filtered, "party")
mixing_matrix_sep20 <- mixingm(net_clicksep20_filtered, "party")
mixing_matrix_oct20 <- mixingm(net_clickoct20_filtered, "party")
mixing_matrix_nov20 <- mixingm(net_clicknov20_filtered, "party")
mixing_matrix_dec20 <- mixingm(net_clickdec20_filtered, "party")
mixing_matrix_jan21 <- mixingm(net_clickjan21_filtered, "party")
mixing_matrix_feb21 <- mixingm(net_clickfeb21_filtered, "party")
mixing_matrix_mar21 <- mixingm(net_clickmar21_filtered, "party")
mixing_matrix_apr21 <- mixingm(net_clickapr21_filtered, "party")
mixing_matrix_may21 <- mixingm(net_clickmay21_filtered, "party")
mixing_matrix_jun21 <- mixingm(net_clickjun21_filtered, "party")
mixing_matrix_jul21 <- mixingm(net_clickjul21_filtered, "party")
mixing_matrix_aug21 <- mixingm(net_clickaug21_filtered, "party")
mixing_matrix_sep21 <- mixingm(net_clicksep21_filtered, "party")
mixing_matrix_oct21 <- mixingm(net_clickoct21_filtered, "party")
mixing_matrix_nov21 <- mixingm(net_clicknov21_filtered, "party")

# Combine the mixing matrices into a list
matrices_list <- list(November_19 = mixing_matrix_nov19, December_19 = mixing_matrix_dec19, January_20 = mixing_matrix_jan20, February_20 = mixing_matrix_feb20, March_20 = mixing_matrix_mar20, April_20 = mixing_matrix_apr20, May_20 = mixing_matrix_may20, June_20 = mixing_matrix_jun20, July_20 = mixing_matrix_jul20, August_20 = mixing_matrix_aug20, September_20 = mixing_matrix_sep20, October_20 = mixing_matrix_oct20, November_20 = mixing_matrix_nov20, December_20 = mixing_matrix_dec20, January_21 = mixing_matrix_jan21, February_21 = mixing_matrix_feb21, March_21 = mixing_matrix_mar21, April_21 = mixing_matrix_apr21, May_21 = mixing_matrix_may21, June_21 = mixing_matrix_jun21, July_21 = mixing_matrix_jul21, August_21 = mixing_matrix_aug21, September_21 = mixing_matrix_sep21, October_21 = mixing_matrix_oct21, November_21 = mixing_matrix_nov21)

# Definen function to extract counts from mixing matrices
extract_counts <- function(matrix, month) {
  data.frame(
    Month = month,
    "Democrat to Democrat" = matrix["Democrat", "Democrat"],
    "Democrat to Republican" = matrix["Democrat", "Republican"],
    "Republican to Democrat" = matrix["Republican", "Democrat"],
    "Republican to Republican" = matrix["Republican", "Republican"]
  )
}

# Turn the results into a dataframe
results <- bind_rows(lapply(names(matrices_list), function(month) {
  extract_counts(matrices_list[[month]], month)
}))

# Factorise month
results$Month <- factor(results$Month, levels = c(
  "November_19", "December_19",
  "January_20", "February_20", "March_20", "April_20", "May_20", "June_20", "July_20", "August_20", "September_20", "October_20", "November_20", "December_20",
  "January_21", "February_21", "March_21", "April_21", "May_21", "June_21", "July_21", "August_21", "September_21", "October_21", "November_21"
))

# Pivot long
results_long <- results %>%
  gather(key = "Interaction", value = "Count", -Month)

# Factorise the type of link
results_long$Interaction <- factor(results_long$Interaction, levels = c(
  "Democrat.to.Democrat",
  "Democrat.to.Republican",
  "Republican.to.Democrat",
  "Republican.to.Republican"
))

# Set custom y breaks, x-axis labels, legend labels and colors
y_breaks <- pretty(results_long$Count, n = 5)

custom_labels <- c("November '19", "December '19",
  "January '20", "February '20", "March '20", "April '20", "May '20", "June '20", "July '20", "August '20", "September '20", "October '20", "November '20", "December '20",
  "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21", "September '21", "October '21", "November '21")

custom_legend_labels <- c("Democrat to Democrat", "Democrat to Republican", "Republican to Democrat", "Republican to Republican")

custom_colors <- c(
  "Democrat.to.Democrat" = "dodgerblue", 
  "Republican.to.Democrat" = "pink", 
  "Democrat.to.Republican" = "purple", 
  "Republican.to.Republican" = "red"
)

# Plot the number of edges differentiated by type
ggplot(results_long, aes(x = Month, y = Count, color = Interaction, group = Interaction)) +
  geom_line() +
  geom_point(size = 1) +
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.4) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.4) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = -1, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -3, color = "black", family = "Times New Roman", size = 6) +
  labs(title = "Figure 1. Count of Edges included in Wikipedia Hyperlink Networks",
       x = "Month",
       y = "Edge Count", 
       color = "Link Type") +
  scale_x_discrete(labels = custom_labels) +
  scale_y_continuous(breaks = y_breaks) +
  scale_color_manual(values = custom_colors, labels = custom_legend_labels) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 15, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    plot.title = element_text(size = 25, family = "Times New Roman", hjust = 0.5),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    legend.text = element_text(size = 15, family = "Times New Roman"),
    legend.title = element_text(size = 20, family = "Times New Roman")
  )
```

```{r modularity}
# Define a function to calculate modularity for a given network and party membership
calculate_modularity <- function(network, party_levels = c("Democrat", "Republican")) {
  membership <- V(network)$party
  membership <- as.numeric(factor(membership, levels = party_levels))
  mod <- modularity(network, membership)
  return(mod)
}

# Create data frame and calculate modularity for each filtered network
modularity_scores <- data.frame(
  Month = c(
    "November '19", "December '19", "January '20", "February '20", "March '20", "April '20", "May '20", "June '20",
    "July '20", "August '20", "September '20", "October '20", "November '20", "December '20",
    "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21",
    "September '21", "October '21", "November '21"
  ),
  Modularity = c(
    calculate_modularity(net_clicknov19_filtered), calculate_modularity(net_clickdec19_filtered), calculate_modularity(net_clickjan20_filtered),
    calculate_modularity(net_clickfeb20_filtered), calculate_modularity(net_clickmar20_filtered), calculate_modularity(net_clickapr20_filtered),
    calculate_modularity(net_clickmay20_filtered), calculate_modularity(net_clickjun20_filtered), calculate_modularity(net_clickjul20_filtered),
    calculate_modularity(net_clickaug20_filtered), calculate_modularity(net_clicksep20_filtered), calculate_modularity(net_clickoct20_filtered),
    calculate_modularity(net_clicknov20_filtered), calculate_modularity(net_clickdec20_filtered), calculate_modularity(net_clickjan21_filtered),
    calculate_modularity(net_clickfeb21_filtered), calculate_modularity(net_clickmar21_filtered), calculate_modularity(net_clickapr21_filtered),
    calculate_modularity(net_clickmay21_filtered), calculate_modularity(net_clickjun21_filtered), calculate_modularity(net_clickjul21_filtered),
    calculate_modularity(net_clickaug21_filtered), calculate_modularity(net_clicksep21_filtered), calculate_modularity(net_clickoct21_filtered),
    calculate_modularity(net_clicknov21_filtered)
  )
)

# Factorise month
modularity_scores$Month <- factor(modularity_scores$Month, levels = modularity_scores$Month)
average_modularity <- mean(modularity_scores$Modularity, na.rm = TRUE)

# Plot the modularity scores
ggplot(modularity_scores, aes(x = Month, y = Modularity)) +
  geom_point(size = 0.8, color = "purple") +  # Add points
  geom_line(aes(group = 1), color = "purple") +  # Connect points with lines
  geom_hline(yintercept = average_modularity, linetype = "solid", color = "darkorange3", alpha = 0.6) + 
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.4) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.4) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = -1, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -3, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = Inf, y = average_modularity, label = "Average Modularity", vjust = 1.5, hjust = 1, color = "darkorange3", family = "Times New Roman", size = 6) +
  labs(x = "Month", y = "Modularity", title = "Figure 2. Modularity Scores for Empirical Networks") +
  theme_minimal() +  # Minimal theme
  theme(
    axis.text.x = element_text(size = 15, angle = 45, hjust = 1, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    plot.title = element_text(size = 25, family = "Times New Roman", hjust = 0.5),
    legend.text = element_text(family = "Times New Roman"),
    legend.title = element_text(family = "Times New Roman")
  ) +
  scale_y_continuous(limits = c(0, 0.5))
```

```{r boundary_polarisation}
# Define the function to compute Spearman correlation of weighted degrees and cross-boundary connections
calculate_spearman_correlation <- function(graph) {
  party_labels <- V(graph)$party
  
  community <- party_labels
  
  # Calculate the degrees of each node in the graph
  degrees <- strength(
    graph, mode = "out", weights = E(graph)$weight)
  
  # Define a nested function to compute cross-boundary connections
  cross_boundary_connections <- function(graph, community) {
    sapply(V(graph), function(node) {
      neighbors <- neighbors(graph, node, mode = "out") # Find all outgoing neighbors
      # Identify the edges connecting the current node to its neighbors:
      edge_ids <- E(graph)[.from(node) & .to(neighbors)]
      # Sum the weights of links where neighboring nodes are in different communities:
      sum(E(graph)$weight[
        edge_ids][community[neighbors] != community[node]])
    })
  }
  
  # Calculate cross-boundary connections for the given graph and community membership
  db <- cross_boundary_connections(graph, community)
  
  # Rank the degrees in descending order
  rank_r <- rank(-degrees)
  
  # Rank the cross-boundary connections in descending order
  rank_rb <- rank(-db)

  # Calculate the Spearman correlation coefficient between the two ranks
  rho <- cor(rank_r, rank_rb, method = "spearman")
  
  # Define function to calculate polarization for a specific party
  calculate_party_polarization <- function(party) {
    # Get the indices of nodes from the specified party
    party_nodes <- which(party_labels == party)
    if (length(party_nodes) < 2) {
      return(NA)
    }
    # Calculate the weighted degrees for the identified nodes:
    party_degrees <- strength(
      graph, vids = party_nodes, weights = E(graph)$weight)
    # Calculate the cross-boundary connections for the identified nodes:
    party_db <- db[party_nodes]
    # Rank both measurements in decreasing order:
    party_rank_r <- rank(-party_degrees)
    party_rank_rb <- rank(-party_db)
    # Calculate the Spearman correlation:
    rho_party <- cor(party_rank_r, party_rank_rb, method = "spearman")
    return(rho_party)
  }
  
  # Calculate polarization for Republicans
  rho_republican <- calculate_party_polarization("Republican")
  
  # Calculate polarization for Democrats
  rho_democrat <- calculate_party_polarization("Democrat")

  
  # Return the Spearman correlation coefficients
  return(list(
    overall = rho,
    republican = rho_republican,
    democrat = rho_democrat
  ))
}

# Calculate boundary polarisation for each month
bp_nov19 <- calculate_spearman_correlation(net_clicknov19_filtered)
bp_dec19 <- calculate_spearman_correlation(net_clickdec19_filtered)
bp_jan20 <- calculate_spearman_correlation(net_clickjan20_filtered)
bp_feb20 <- calculate_spearman_correlation(net_clickfeb20_filtered)
bp_mar20 <- calculate_spearman_correlation(net_clickmar20_filtered)
bp_apr20 <- calculate_spearman_correlation(net_clickapr20_filtered)
bp_may20 <- calculate_spearman_correlation(net_clickmay20_filtered)
bp_jun20 <- calculate_spearman_correlation(net_clickjun20_filtered)
bp_jul20 <- calculate_spearman_correlation(net_clickjul20_filtered)
bp_aug20 <- calculate_spearman_correlation(net_clickaug20_filtered)
bp_sep20 <- calculate_spearman_correlation(net_clicksep20_filtered)
bp_oct20 <- calculate_spearman_correlation(net_clickoct20_filtered)
bp_nov20 <- calculate_spearman_correlation(net_clicknov20_filtered)
bp_dec20 <- calculate_spearman_correlation(net_clickdec20_filtered)
bp_jan21 <- calculate_spearman_correlation(net_clickjan21_filtered)
bp_feb21 <- calculate_spearman_correlation(net_clickfeb21_filtered)
bp_mar21 <- calculate_spearman_correlation(net_clickmar21_filtered)
bp_apr21 <- calculate_spearman_correlation(net_clickapr21_filtered)
bp_may21 <- calculate_spearman_correlation(net_clickmay21_filtered)
bp_jun21 <- calculate_spearman_correlation(net_clickjun21_filtered)
bp_jul21 <- calculate_spearman_correlation(net_clickjul21_filtered)
bp_aug21 <- calculate_spearman_correlation(net_clickaug21_filtered)
bp_sep21 <- calculate_spearman_correlation(net_clicksep21_filtered)
bp_oct21 <- calculate_spearman_correlation(net_clickoct21_filtered)
bp_nov21 <- calculate_spearman_correlation(net_clicknov21_filtered)

# generate random networks for each month
random_net_nov19 <- sample_degseq(out.deg = degree(
  net_clicknov19_filtered, mode='out'), in.deg = degree(
    net_clicknov19_filtered, mode='in'), method = "simple")

random_net_dec19 <- sample_degseq(out.deg = degree(
  net_clickdec19_filtered, mode='out'), in.deg = degree(
    net_clickdec19_filtered, mode='in'), method = "simple")

random_net_jan20 <- sample_degseq(out.deg = degree(
  net_clickjan20_filtered, mode='out'), in.deg = degree(
    net_clickjan20_filtered, mode='in'), method = "simple")

random_net_feb20 <- sample_degseq(out.deg = degree(
  net_clickfeb20_filtered, mode='out'), in.deg = degree(
    net_clickfeb20_filtered, mode='in'), method = "simple")

random_net_mar20 <- sample_degseq(out.deg = degree(
  net_clickmar20_filtered, mode='out'), in.deg = degree(
    net_clickmar20_filtered, mode='in'), method = "simple")

random_net_apr20 <- sample_degseq(out.deg = degree(
  net_clickapr20_filtered, mode='out'), in.deg = degree(
    net_clickapr20_filtered, mode='in'), method = "simple")

random_net_may20 <- sample_degseq(out.deg = degree(
  net_clickmay20_filtered, mode='out'), in.deg = degree(
    net_clickmay20_filtered, mode='in'), method = "simple")

random_net_jun20 <- sample_degseq(out.deg = degree(
  net_clickjun20_filtered, mode='out'), in.deg = degree(
    net_clickjun20_filtered, mode='in'), method = "simple")

random_net_jul20 <- sample_degseq(out.deg = degree(
  net_clickjul20_filtered, mode='out'), in.deg = degree(
    net_clickjul20_filtered, mode='in'), method = "simple")

random_net_aug20 <- sample_degseq(out.deg = degree(
  net_clickaug20_filtered, mode='out'), in.deg = degree(
    net_clickaug20_filtered, mode='in'), method = "simple")

random_net_sep20 <- sample_degseq(out.deg = degree(
  net_clicksep20_filtered, mode='out'), in.deg = degree(
    net_clicksep20_filtered, mode='in'), method = "simple")

random_net_oct20 <- sample_degseq(out.deg = degree(
  net_clickoct20_filtered, mode='out'), in.deg = degree(
    net_clickoct20_filtered, mode='in'), method = "simple")

random_net_nov20 <- sample_degseq(out.deg = degree(
  net_clicknov20_filtered, mode='out'), in.deg = degree(
    net_clicknov20_filtered, mode='in'), method = "simple")

random_net_dec20 <- sample_degseq(out.deg = degree(
  net_clickdec20_filtered, mode='out'), in.deg = degree(
    net_clickdec20_filtered, mode='in'), method = "simple")

random_net_jan21 <- sample_degseq(out.deg = degree(
  net_clickjan21_filtered, mode='out'), in.deg = degree(
    net_clickjan21_filtered, mode='in'), method = "simple")

random_net_feb21 <- sample_degseq(out.deg = degree(
  net_clickfeb21_filtered, mode='out'), in.deg = degree(
    net_clickfeb21_filtered, mode='in'), method = "simple")

random_net_mar21 <- sample_degseq(out.deg = degree(
  net_clickmar21_filtered, mode='out'), in.deg = degree(
    net_clickmar21_filtered, mode='in'), method = "simple")

random_net_apr21 <- sample_degseq(out.deg = degree(
  net_clickapr21_filtered, mode='out'), in.deg = degree(
    net_clickapr21_filtered, mode='in'), method = "simple")

random_net_may21 <- sample_degseq(out.deg = degree(
  net_clickmay21_filtered, mode='out'), in.deg = degree(
    net_clickmay21_filtered, mode='in'), method = "simple")

random_net_jun21 <- sample_degseq(out.deg = degree(
  net_clickjun21_filtered, mode='out'), in.deg = degree(
    net_clickjun21_filtered, mode='in'), method = "simple")

random_net_jul21 <- sample_degseq(out.deg = degree(
  net_clickjul21_filtered, mode='out'), in.deg = degree(
    net_clickjul21_filtered, mode='in'), method = "simple")

random_net_aug21 <- sample_degseq(out.deg = degree(
  net_clickaug21_filtered, mode='out'), in.deg = degree(
    net_clickaug21_filtered, mode='in'), method = "simple")

random_net_sep21 <- sample_degseq(out.deg = degree(
  net_clicksep21_filtered, mode='out'), in.deg = degree(
    net_clicksep21_filtered, mode='in'), method = "simple")

random_net_oct21 <- sample_degseq(out.deg = degree(
  net_clickoct21_filtered, mode='out'), in.deg = degree(
    net_clickoct21_filtered, mode='in'), method = "simple")

random_net_nov21 <- sample_degseq(out.deg = degree(
  net_clicknov21_filtered, mode='out'), in.deg = degree(
    net_clicknov21_filtered, mode='in'), method = "simple")

# Define a function to assign party and weight attributes
# to random networks and calculate the boundary polarisation
assign_attributes_and_calculate_correlation <- function(random_net, original_net, correlation = TRUE) {
  
  # Get the name of the random network
  random_net_name <- deparse(substitute(random_net))
  
  # Assign the 'party' attribute from the original network to the random network
  party_attr <- vertex_attr(original_net, name = "party")
  random_net <- set_vertex_attr(random_net, name = "party", value = party_attr)
  
  # Assign the 'weight' attribute from the original network to the random network
  weight_attr <- edge_attr(original_net, name = "weight")
  random_net <- set_edge_attr(random_net, name = "weight", value = weight_attr)
  
  # Save the new random network to the old name
  assign(random_net_name, random_net, envir = .GlobalEnv)
  
  # If desired, also calculate the boundary polarisation
  if (correlation == TRUE) {
   output <- calculate_spearman_correlation(random_net) 
   return(output)
  }
}

bp_random_nov19 <- assign_attributes_and_calculate_correlation(random_net_nov19, net_clicknov19_filtered)
bp_random_dec19 <- assign_attributes_and_calculate_correlation(random_net_dec19, net_clickdec19_filtered)
bp_random_jan20 <- assign_attributes_and_calculate_correlation(random_net_jan20, net_clickjan20_filtered)
bp_random_feb20 <- assign_attributes_and_calculate_correlation(random_net_feb20, net_clickfeb20_filtered)
bp_random_mar20 <- assign_attributes_and_calculate_correlation(random_net_mar20, net_clickmar20_filtered)
bp_random_apr20 <- assign_attributes_and_calculate_correlation(random_net_apr20, net_clickapr20_filtered)
bp_random_may20 <- assign_attributes_and_calculate_correlation(random_net_may20, net_clickmay20_filtered)
bp_random_jun20 <- assign_attributes_and_calculate_correlation(random_net_jun20, net_clickjun20_filtered)
bp_random_jul20 <- assign_attributes_and_calculate_correlation(random_net_jul20, net_clickjul20_filtered)
bp_random_aug20 <- assign_attributes_and_calculate_correlation(random_net_aug20, net_clickaug20_filtered)
bp_random_sep20 <- assign_attributes_and_calculate_correlation(random_net_sep20, net_clicksep20_filtered)
bp_random_oct20 <- assign_attributes_and_calculate_correlation(random_net_oct20, net_clickoct20_filtered)
bp_random_nov20 <- assign_attributes_and_calculate_correlation(random_net_nov20, net_clicknov20_filtered)
bp_random_dec20 <- assign_attributes_and_calculate_correlation(random_net_dec20, net_clickdec20_filtered)
bp_random_jan21 <- assign_attributes_and_calculate_correlation(random_net_jan21, net_clickjan21_filtered)
bp_random_feb21 <- assign_attributes_and_calculate_correlation(random_net_feb21, net_clickfeb21_filtered)
bp_random_mar21 <- assign_attributes_and_calculate_correlation(random_net_mar21, net_clickmar21_filtered)
bp_random_apr21 <- assign_attributes_and_calculate_correlation(random_net_apr21, net_clickapr21_filtered)
bp_random_may21 <- assign_attributes_and_calculate_correlation(random_net_may21, net_clickmay21_filtered)
bp_random_jun21 <- assign_attributes_and_calculate_correlation(random_net_jun21, net_clickjun21_filtered)
bp_random_jul21 <- assign_attributes_and_calculate_correlation(random_net_jul21, net_clickjul21_filtered)
bp_random_aug21 <- assign_attributes_and_calculate_correlation(random_net_aug21, net_clickaug21_filtered)
bp_random_sep21 <- assign_attributes_and_calculate_correlation(random_net_sep21, net_clicksep21_filtered)
bp_random_oct21 <- assign_attributes_and_calculate_correlation(random_net_oct21, net_clickoct21_filtered)
bp_random_nov21 <- assign_attributes_and_calculate_correlation(random_net_nov21, net_clicknov21_filtered)
```

```{r bp_visualisation}
# Create a data frame with the boundary polarisation scores
boundary_polarisation_scores <- data.frame(
  Month = c("November '19", "December '19", "January '20", "February '20", "March '20", "April '20", "May '20", "June '20", "July '20", "August '20", "September '20", "October '20", "November '20", "December '20", "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21", "September '21", "October '21", "November '21"),
  Boundary_Polarisation = c(bp_nov19[1]$overall, bp_dec19[1]$overall, bp_jan20[1]$overall, bp_feb20[1]$overall, bp_mar20[1]$overall, bp_apr20[1]$overall, bp_may20[1]$overall, bp_jun20[1]$overall, bp_jul20[1]$overall, bp_aug20[1]$overall, bp_sep20[1]$overall, bp_oct20[1]$overall, bp_nov20[1]$overall, bp_dec20[1]$overall, bp_jan21[1]$overall, bp_feb21[1]$overall, bp_mar21[1]$overall, bp_apr21[1]$overall, bp_may21[1]$overall, bp_jun21[1]$overall, bp_jul21[1]$overall, bp_aug21[1]$overall, bp_sep21[1]$overall, bp_oct21[1]$overall, bp_nov21[1]$overall),
  Republican = c(bp_nov19[2]$republican, bp_dec19[2]$republican, bp_jan20[2]$republican, bp_feb20[2]$republican, bp_mar20[2]$republican, bp_apr20[2]$republican, bp_may20[2]$republican, bp_jun20[2]$republican, bp_jul20[2]$republican, bp_aug20[2]$republican, bp_sep20[2]$republican, bp_oct20[2]$republican, bp_nov20[2]$republican, bp_dec20[2]$republican, bp_jan21[2]$republican, bp_feb21[2]$republican, bp_mar21[2]$republican, bp_apr21[2]$republican, bp_may21[2]$republican, bp_jun21[2]$republican, bp_jul21[2]$republican, bp_aug21[2]$republican, bp_sep21[2]$republican, bp_oct21[2]$republican, bp_nov21[2]$republican),
  Democrat = c(bp_nov19[3]$democrat, bp_dec19[3]$democrat, bp_jan20[3]$democrat, bp_feb20[3]$democrat, bp_mar20[3]$democrat, bp_apr20[3]$democrat, bp_may20[3]$democrat, bp_jun20[3]$democrat, bp_jul20[3]$democrat, bp_aug20[3]$democrat, bp_sep20[3]$democrat, bp_oct20[3]$democrat, bp_nov20[3]$democrat, bp_dec20[3]$democrat, bp_jan21[3]$democrat, bp_feb21[3]$democrat, bp_mar21[3]$democrat, bp_apr21[3]$democrat, bp_may21[3]$democrat, bp_jun21[3]$democrat, bp_jul21[3]$democrat, bp_aug21[3]$democrat, bp_sep21[3]$democrat, bp_oct21[3]$democrat, bp_nov21[3]$democrat),
  Random = c(bp_random_nov19[1]$overall, bp_random_dec19[1]$overall, bp_random_jan20[1]$overall, bp_random_feb20[1]$overall, bp_random_mar20[1]$overall, bp_random_apr20[1]$overall, bp_random_may20[1]$overall, bp_random_jun20[1]$overall, bp_random_jul20[1]$overall, bp_random_aug20[1]$overall, bp_random_sep20[1]$overall, bp_random_oct20[1]$overall, bp_random_nov20[1]$overall, bp_random_dec20[1]$overall, bp_random_jan21[1]$overall, bp_random_feb21[1]$overall, bp_random_mar21[1]$overall, bp_random_apr21[1]$overall, bp_random_may21[1]$overall, bp_random_jun21[1]$overall, bp_random_jul21[1]$overall, bp_random_aug21[1]$overall, bp_random_sep21[1]$overall, bp_random_oct21[1]$overall, bp_random_nov21[1]$overall),
  Random_Republican = c(bp_random_nov19[2]$republican, bp_random_dec19[2]$republican, bp_random_jan20[2]$republican, bp_random_feb20[2]$republican, bp_random_mar20[2]$republican, bp_random_apr20[2]$republican, bp_random_may20[2]$republican, bp_random_jun20[2]$republican, bp_random_jul20[2]$republican, bp_random_aug20[2]$republican, bp_random_sep20[2]$republican, bp_random_oct20[2]$republican, bp_random_nov20[2]$republican, bp_random_dec20[2]$republican, bp_random_jan21[2]$republican, bp_random_feb21[2]$republican, bp_random_mar21[2]$republican, bp_random_apr21[2]$republican, bp_random_may21[2]$republican, bp_random_jun21[2]$republican, bp_random_jul21[2]$republican, bp_random_aug21[2]$republican, bp_random_sep21[2]$republican, bp_random_oct21[2]$republican, bp_random_nov21[2]$republican),
  Random_Democrat = c(bp_random_nov19[3]$democrat, bp_random_dec19[3]$democrat, bp_random_jan20[3]$democrat, bp_random_feb20[3]$democrat, bp_random_mar20[3]$democrat, bp_random_apr20[3]$democrat, bp_random_may20[3]$democrat, bp_random_jun20[3]$democrat, bp_random_jul20[3]$democrat, bp_random_aug20[3]$democrat, bp_random_sep20[3]$democrat, bp_random_oct20[3]$democrat, bp_random_nov20[3]$democrat, bp_random_dec20[3]$democrat, bp_random_jan21[3]$democrat, bp_random_feb21[3]$democrat, bp_random_mar21[3]$democrat, bp_random_apr21[3]$democrat, bp_random_may21[3]$democrat, bp_random_jun21[3]$democrat, bp_random_jul21[3]$democrat, bp_random_aug21[3]$democrat, bp_random_sep21[3]$democrat, bp_random_oct21[3]$democrat, bp_random_nov21[3]$democrat)
)

# Factorise month
boundary_polarisation_scores$Month <- factor(
  boundary_polarisation_scores$Month,
  levels = c("November '19", "December '19", "January '20", "February '20", "March '20", "April '20", "May '20", "June '20", "July '20", "August '20", "September '20", "October '20", "November '20", "December '20", "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21", "September '21", "October '21", "November '21")
)

# Define custom colors
custom_colors <- c("Random Networks" = "darkorange", "Empirical Networks" = "purple")

# Plot the results
ggplot(boundary_polarisation_scores, aes(x = Month)) +
  geom_line(aes(y = Random, color = "Random Networks", group = 1)) +  # Color and label for random networks
  geom_line(aes(y = Boundary_Polarisation, color = "Empirical Networks", group = 2)) +  # Color and label for empirical networks
  geom_point(aes(y = Random, color = "Random Networks"), size = 1) +  # Smaller points for random networks
  geom_point(aes(y = Boundary_Polarisation, color = "Empirical Networks"), size = 1) +  # Smaller points for empirical networks
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.4) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.4) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = -1, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -4, color = "black", family = "Times New Roman", size = 6) +
  labs(x = "Month", y = "Spearman's Rho", title = "Figure 3. Boundary Polarisation of Empirical and Random Networks", color = "Network Type") +
  scale_color_manual(values = custom_colors) +  # Set custom colors for lines and points
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 15, angle = 45, hjust = 1, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    plot.title = element_text(size = 25, hjust = 0.5, family = "Times New Roman"),
    legend.title = element_text(size = 20, family = "Times New Roman"),
    legend.text = element_text(size = 15, family = "Times New Roman")
  ) +
  scale_y_continuous(limits = c(0, 0.5))
```

```{r bp_both_parties}
# Reshape the data frame from previous chunk for plotting
boundary_polarisation_long <- boundary_polarisation_scores %>%
  pivot_longer(cols = c(Random, Boundary_Polarisation, Republican, Democrat),
               names_to = "Metric",
               values_to = "Value") %>%
  mutate(Metric = factor(Metric, levels = c("Random", "Boundary_Polarisation", "Republican", "Democrat")))

# Define custom colors
custom_colors <- c("Random" = "darkorange", 
                   "Boundary_Polarisation" = "purple",
                   "Republican" = "red",
                   "Democrat" = "blue")

# Plot the results with differentiation by party
ggplot(boundary_polarisation_long, aes(x = Month, y = Value, color = Metric, group = Metric)) +
  geom_line(size = 1) +  # Line for each Metric
  geom_point(size = 2) +  # Points for each Metric
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.4) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.4) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = -1, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -4, color = "black", family = "Times New Roman", size = 6) +
  labs(x = "Month", y = "Spearman's Rho", title = "Figure B1. Boundary Polarisation of Empirical and Random Networks by Party", color = "Metric") +
  scale_color_manual(values = custom_colors) +  # Set custom colors for lines and points
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 15, angle = 45, hjust = 1, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    plot.title = element_text(size = 25, hjust = 0.5, family = "Times New Roman"),
    legend.title = element_text(size = 20, family = "Times New Roman"),
    legend.text = element_text(size = 15, family = "Times New Roman")
  ) +
  scale_y_continuous(limits = c(0, 0.5))
```



```{r save_image2}
save.image("data/click_networks_rw.RData")
save.image("data/click_networks_rw2.RData")

load("data/click_networks_rw2.RData")
```

```{r define_pv_function}
# Define a function to fetch the total page views for a given article
page_view_month <- function(article_name, start, end) {
  # Construct the URL for the API request
  url <- paste0(
    "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/all-agents/",
    article_name,
    "/daily/",
    start,
    "/",
    end
  )
  
  # Make the GET request
  response <- GET(url, add_headers(`accept` = "application/json"))
  
  # Check if the request was successful
  if (status_code(response) == 200) {
    # Parse the JSON content
    content_data <- content(response, "parsed")
    # Extract views from each day and sum them
    total_views <- sum(sapply(content_data$items, function(item) item$views))
    return(total_views)
  } else { # If the request was not successful, return NA
    return(NA)
  }
}

# Pages which appeared in the top viewed pages but were deemed irrelevant for Democrats
pages_to_filter <- c(
  "call_of_duty:_black_ops_cold_war", "borat_subsequent_moviefilm", "joe_exotic",
  "stephen_colbert", "billie_eilish", "ken_burns", "tom_brady",
  "john_wane_gacy", "ken_jennings", "beyonc", "stephen_king",
  "jennifer_garner", "gilian_anderson", "jodie_foster", "caitlyn_jenner",
  "anthony_fauci", "space_shuttle_columbia_disaster", "taxi_driver",
  "buzz_aldrin", "ted_bundy", "wyatt_earp", "gadsden_flag", "vermin_supreme",
  "alec_baldwin", "jennifer_garner", "ku_klux_klan", "stephen_king",
  "columbine_high_school_massacre", "jon_bon_jovi", "monica_lewinsky",
  "guantanamo_bay_detention_camp", "warren_buffett", "2012_benghazi_attack",
  "jefferson_davis", "chicago_seven", "aretha_franklin", "ken_jennings",
  "henry_fonda", "2004_united_states_presidential_election",
  "timeline_of_russian_interference_in_the_2016_united_states_elections",
  "1984_united_states_presidential_election", "1988_united_states_presidential_election",
  "1980_united_states_presidential_election", "1976_united_states_presidential_election",
  "1964_united_states_presidential_election", "faithless_electors_in_the_2016_united_states_presidential_election", "1860_united_states_presidential_election", "1864_united_states_presidential_election",
  "1972_united_states_presidential_election", "1936_united_states_presidential_election",
  "1944_united_states_presidential_election", "1940_united_states_presidential_election",
  "1932_united_states_presidential_election", "1928_united_states_presidential_election",
  "1920_united_states_presidential_election", "iraq_war", "gulf_war",
  "reform_party_of_the_united_states_of_america", "constitution_party_(united_states)",
  "seth_macfarlane", "rocky_de_la_fuente", "billy_ray_cyrus", "deepwater_horizon_oil_spill",
  "killing_of_osama_bin_laden", "john_wayne_gacy" 
)

# Pages which appeared in the top viewed pages but were deemed irrelevant for Republicans
pages_to_filter_rep <- c(
  "call_of_duty:_black_ops_cold_war", "borat_subsequent_moviefilm",
  "joe_exotic", "stephen_colbert", "billie_eilish", "ken_burns", "tom_brady",
  "john_wane_gacy", "ken_jennings", "beyonc", "stephen_king", "jennifer_garner",
  "gilian_anderson", "jodie_foster", "caitlyn_jenner", "anthony_fauci",
  "space_shuttle_columbia_disaster", "taxi_driver", "buzz_aldrin", "ted_bundy",
  "wyatt_earp", "gadsden_flag", "vermin_supreme", "alec_baldwin",
  "jennifer_garner", "ku_klux_klan", "stephen_king", "columbine_high_school_massacre",
  "jon_bon_jovi", "monica_lewinsky", "guantanamo_bay_detention_camp", "warren_buffett",
  "2012_benghazi_attack", "jefferson_davis", "chicago_seven", "aretha_franklin",
  "ken_jennings", "henry_fonda", "2004_united_states_presidential_election", "timeline_of_russian_interference_in_the_2016_united_states_elections",
  "1984_united_states_presidential_election", "1988_united_states_presidential_election",
  "1980_united_states_presidential_election", "1976_united_states_presidential_election",
  "1964_united_states_presidential_election", "faithless_electors_in_the_2016_united_states_presidential_election", "1860_united_states_presidential_election", "1864_united_states_presidential_election",
  "1972_united_states_presidential_election", "1936_united_states_presidential_election",
  "1944_united_states_presidential_election", "1940_united_states_presidential_election",
  "1932_united_states_presidential_election", "1928_united_states_presidential_election",
  "1920_united_states_presidential_election", "iraq_war", "gulf_war", "hillary_clinton", "reform_party_of_the_united_states_of_america", "constitution_party_(united_states)",
  "space_shuttle_columbia_disaster"
)
```

```{r page_views_sep}
# Loop through all republican pages
page_views_republican_sep <- list()
for (i in republican_pages) {
  # Get page view data for the specified time frame
  page_views_republican_sep[[i]] <- page_view_month(i, "20200901", "20200930")
  if (is.na(page_views_republican_sep[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

# Loop through all democrat pages
page_views_democrat_sep <- list()
for (i in democrat_pages) {
  # Get page view data for the specified time frame
  page_views_democrat_sep[[i]] <- page_view_month(i, "20200901", "20200930")
  if (is.na(page_views_democrat_sep[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

updated_rep_pv_list_sep <- list()
# Iterate through the original list to standardise all page names
for (original_name in names(page_views_republican_sep)) {
  # Retrieve the value associated with the original name
  page_views <- page_views_republican_sep[[original_name]]
  
  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)
  
  # Store the value under the new standardized name in the updated list
  updated_rep_pv_list_sep[[standardized_name]] <- page_views
}

# Same for democratic pages
updated_dem_pv_list_sep <- list()
for (original_name in names(page_views_democrat_sep)) {
  # Retrieve the value associated with the original name
  page_views <- page_views_democrat_sep[[original_name]]
  
  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)
  
  # Store the value under the new standardized name in the updated list
  updated_dem_pv_list_sep[[standardized_name]] <- page_views
}

# Get page names from the network vertices
network_names_sep <- V(net_clicksep20_filtered)$name

# Match the names of the network vertices with the page views
matched_names_rep_sep <- network_names_sep[
  network_names_sep %in% names(updated_rep_pv_list_sep)]
page_views_republican_filtered_sep <- updated_rep_pv_list_sep[matched_names_rep_sep]
matched_names_dem_sep <- network_names_sep[
  network_names_sep %in% names(updated_dem_pv_list_sep)]
page_views_democrat_filtered_sep <- updated_dem_pv_list_sep[matched_names_dem_sep]

# Order by descending page views
page_views_republican_filtered_sep <- page_views_republican_filtered_sep[
  order(unlist(page_views_republican_filtered_sep), decreasing = TRUE)]
page_views_democrat_filtered_sep <- page_views_democrat_filtered_sep[
  order(unlist(page_views_democrat_filtered_sep), decreasing = TRUE)]

# Remove pages that are deemed irrelevant
page_views_democrat_filtered_sep <- page_views_democrat_filtered_sep[
  !(names(page_views_democrat_filtered_sep) %in% pages_to_filter)]
page_views_republican_filtered_sep <- page_views_republican_filtered_sep[
  !(names(page_views_republican_filtered_sep) %in% pages_to_filter_rep)]

# Extract page names of the first 100 pages
page_names_republican_sep <- names(page_views_republican_filtered_sep)[1:100]
page_names_democrat_sep <- names(page_views_democrat_filtered_sep)[1:100]
```

```{r page_views_oct}
# Loop through all republican pages
page_views_republican_oct <- list()
for (i in republican_pages) {
  # Get page view data for the specified time frame
  page_views_republican_oct[[i]] <- page_view_month(i, "20201001", "20201031")
  if (is.na(page_views_republican_oct[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

# Loop through all democrat pages
page_views_democrat_oct <- list()
for (i in democrat_pages) {
  # Get page view data for the specified time frame
  page_views_democrat_oct[[i]] <- page_view_month(i, "20201001", "20201031")
  if (is.na(page_views_democrat_oct[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

updated_rep_pv_list_oct <- list()
# Iterate through the original list to standardise all page names
for (original_name in names(page_views_republican_oct)) {
  # Retrieve the value associated with the original name
  page_views <- page_views_republican_oct[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_rep_pv_list_oct[[standardized_name]] <- page_views
}

# Same for democratic pages
updated_dem_pv_list_oct <- list()
# Iterate through the original list to standardise all page names
for (original_name in names(page_views_democrat_oct)) {
  # Retrieve the value associated with the original name
  page_views <- page_views_democrat_oct[[original_name]]
  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)
  # Store the value under the new standardized name in the updated list
  updated_dem_pv_list_oct[[standardized_name]] <- page_views
}

# Extract names from the network vertices
network_names_oct <- V(net_clickoct20_filtered)$name

# Match the names of the network vertices with the page views
matched_names_rep_oct <- network_names_oct[
  network_names_oct %in% names(updated_rep_pv_list_oct)]
page_views_republican_filtered_oct <- updated_rep_pv_list_oct[matched_names_rep_oct]
matched_names_dem_oct <- network_names_oct[
  network_names_oct %in% names(updated_dem_pv_list_oct)]
page_views_democrat_filtered_oct <- updated_dem_pv_list_oct[matched_names_dem_oct]

# Order by descending page views
page_views_republican_filtered_oct <- page_views_republican_filtered_oct[
  order(unlist(page_views_republican_filtered_oct), decreasing = TRUE)]
page_views_democrat_filtered_oct <- page_views_democrat_filtered_oct[
  order(unlist(page_views_democrat_filtered_oct), decreasing = TRUE)]

# Filter out irrelevant pages
page_views_democrat_filtered_oct <- page_views_democrat_filtered_oct[
  !(names(page_views_democrat_filtered_oct) %in% pages_to_filter)]
page_views_republican_filtered_oct <- page_views_republican_filtered_oct[
  !(names(page_views_republican_filtered_oct) %in% pages_to_filter_rep)]

# Extract page names of the first 100 pages
page_names_republican_oct <- names(page_views_republican_filtered_oct)[1:100]
page_names_democrat_oct <- names(page_views_democrat_filtered_oct)[1:100]
```

```{r page_views_nov}
# Loop through all republican pages
page_views_republican <- list()
for (i in republican_pages) {
  # Get page view data for the specified time frame
  page_views_republican[[i]] <- page_view_month(i, "20201101", "20201130")
  if (is.na(page_views_republican[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

# loop through all democrat pages
page_views_democrat <- list()
for (i in democrat_pages) {
  # Get page view data for the specified time frame
  page_views_democrat[[i]] <- page_view_month(i, "20201101", "20201130")
  if (is.na(page_views_democrat[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

updated_rep_pv_list <- list()
# Iterate through the pages to standardise them
for (original_name in names(page_views_republican)) {
  # Retrieve the value associated with the original name
  page_views <- page_views_republican[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_rep_pv_list[[standardized_name]] <- page_views
}

updated_dem_pv_list <- list()
# Iterate through the pages to standardise them
for (original_name in names(page_views_democrat)) {
  # Retrieve the value associated with the original name
  page_views <- page_views_democrat[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_dem_pv_list[[standardized_name]] <- page_views
}

# Extract names from the network vertices
network_names <- V(net_clicknov20_filtered)$name

# Match the names of the network vertices with the page views
matched_names_rep <- network_names[network_names %in% names(updated_rep_pv_list)]
page_views_republican_filtered <- updated_rep_pv_list[matched_names_rep]
matched_names_dem <- network_names[network_names %in% names(updated_dem_pv_list)]
page_views_democrat_filtered <- updated_dem_pv_list[matched_names_dem]

# Filter out the irrelevant pages
page_views_democrat_filtered <- page_views_democrat_filtered[
  !(names(page_views_democrat_filtered) %in% pages_to_filter)]
page_views_republican_filtered <- page_views_republican_filtered[
  !(names(page_views_republican_filtered) %in% pages_to_filter_rep)]

# Order by descending page views
page_views_republican_filtered <- page_views_republican_filtered[
  order(unlist(page_views_republican_filtered), decreasing = TRUE)]
page_views_democrat_filtered <- page_views_democrat_filtered[
  order(unlist(page_views_democrat_filtered), decreasing = TRUE)]

# extract page names of the first 100 pages
page_names_republican <- names(page_views_republican_filtered)[1:100]
page_names_democrat <- names(page_views_democrat_filtered)[1:100]

# Visualise distribution of page views
page_views_df <- data.frame(
  Page = names(page_views_republican_filtered),
  Views = unlist(page_views_republican_filtered)
)

# Remove pages with NA values
page_views_df <- page_views_df[complete.cases(page_views_df), ]

# Order by views, ascending
page_views_df <- page_views_df[order(page_views_df$Views, decreasing = FALSE), ]

ggplot(page_views_df, aes(x = Views)) +
  geom_histogram(binwidth = 0.05, fill = "darkgrey", color = "black") +
  scale_x_log10() +
  theme_minimal() +
  labs(title = "Figure B3. Distribution of Wikipedia Page Views in November 2020",
       x = "Number of Page Views (log scale)",
       y = "Frequency of Pages") +
  theme(
    # Align the title in the center
    plot.title = element_text(size = 25, hjust = 0.5, family = "Times New Roman"),
    # Set the size and font for axis titles
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    # Set the size and font for axis text
    axis.text.x = element_text(size = 15, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman")
  )
```

```{r page_views_dec}
# Loop through all republican pages
page_views_republican_dec <- list()
for (i in republican_pages) {
  # Get page view data for the specified time frame
  page_views_republican_dec[[i]] <- page_view_month(i, "20201201", "20201231")
  if (is.na(page_views_republican_dec[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

# Loop through all democrat pages
page_views_democrat_dec <- list()
for (i in democrat_pages) {
  # Get page view data for the specified time frame
  page_views_democrat_dec[[i]] <- page_view_month(i, "20201201", "20201231")
  if (is.na(page_views_democrat_dec[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

updated_rep_pv_list_dec <- list()
# Iterate through list to standardise all page names
for (original_name in names(page_views_republican_dec)) {
  # Retrieve the value associated with the original name
  page_views_dec <- page_views_republican_dec[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_rep_pv_list_dec[[standardized_name]] <- page_views_dec
}

# Same for democratic pages
updated_dem_pv_list_dec <- list()
for (original_name in names(page_views_democrat_dec)) {
  # Retrieve the value associated with the original name
  page_views_dec <- page_views_democrat_dec[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_dem_pv_list_dec[[standardized_name]] <- page_views_dec
}

# Extract names from the network vertices
network_names_dec <- V(net_clickdec20_filtered)$name

# Match the names of the network vertices with the page views
matched_names_rep_dec <- network_names_dec[network_names_dec %in% names(updated_rep_pv_list_dec)]
page_views_republican_filtered_dec <- updated_rep_pv_list_dec[matched_names_rep_dec]
matched_names_dem_dec <- network_names_dec[network_names_dec %in% names(updated_dem_pv_list_dec)]
page_views_democrat_filtered_dec <- updated_dem_pv_list_dec[matched_names_dem_dec]

# Order by descending page views
page_views_republican_filtered_dec <- page_views_republican_filtered_dec[
  order(unlist(page_views_republican_filtered_dec), decreasing = TRUE)]
page_views_democrat_filtered_dec <- page_views_democrat_filtered_dec[
  order(unlist(page_views_democrat_filtered_dec), decreasing = TRUE)]

# Filter out irrelevant pages
page_views_democrat_filtered_dec <- page_views_democrat_filtered_dec[
  !(names(page_views_democrat_filtered_dec) %in% pages_to_filter)]
page_views_republican_filtered_dec <- page_views_republican_filtered_dec[
  !(names(page_views_republican_filtered_dec) %in% pages_to_filter_rep)]

# Extract page names of the first 1000 pages
page_names_republican_dec <- names(page_views_republican_filtered_dec)[1:100]
page_names_democrat_dec <- names(page_views_democrat_filtered_dec)[1:100]
```

```{r page_views_jan}
# Loop through all republican pages
page_views_republican_jan <- list()
for (i in republican_pages) {
  # Get page view data for the specified time frame
  page_views_republican_jan[[i]] <- page_view_month(i, "20210101", "20210131")
  if (is.na(page_views_republican_jan[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

# Loop through all democrat pages
page_views_democrat_jan <- list()
for (i in democrat_pages) {
  # Get page view data for the specified time frame
  page_views_democrat_jan[[i]] <- page_view_month(i, "20210101", "20210131")
  if (is.na(page_views_democrat_jan[[i]])) {
    # Get page view data for the specified time frame
    print(paste("Failed to fetch data for", i))
    next
  }
}

updated_rep_pv_list_jan <- list()
# Iterate through the list to standardise all page names
for (original_name in names(page_views_republican_jan)) {
  # Retrieve the value associated with the original name
  page_views_jan_rep <- page_views_republican_jan[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_rep_pv_list_jan[[standardized_name]] <- page_views_jan_rep
}

# Same for democratic pages
updated_dem_pv_list_jan <- list()
for (original_name in names(page_views_democrat_jan)) {
  # Retrieve the value associated with the original name
  page_views_jan_dem <- page_views_democrat_jan[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_dem_pv_list_jan[[standardized_name]] <- page_views_jan_dem
}

# Extract names from the network vertices
network_names_jan <- V(net_clickjan21_filtered)$name

# Match the names of the network vertices with the page views
matched_names_rep_jan <- network_names_jan[
  network_names_jan %in% names(updated_rep_pv_list_jan)]
page_views_republican_filtered_jan <- updated_rep_pv_list_jan[matched_names_rep_jan]
matched_names_dem_jan <- network_names_jan[
  network_names_jan %in% names(updated_dem_pv_list_jan)]
page_views_democrat_filtered_jan <- updated_dem_pv_list_jan[matched_names_dem_jan]

# Order by descending page views
page_views_republican_filtered_jan <- page_views_republican_filtered_jan[order(
  unlist(page_views_republican_filtered_jan), decreasing = TRUE)]
page_views_democrat_filtered_jan <- page_views_democrat_filtered_jan[order(
  unlist(page_views_democrat_filtered_jan), decreasing = TRUE)]

# Filter out irrelevant pages
page_views_democrat_filtered_jan <- page_views_democrat_filtered_jan[
  !(names(page_views_democrat_filtered_jan) %in% pages_to_filter)]
page_views_republican_filtered_jan <- page_views_republican_filtered_jan[
  !(names(page_views_republican_filtered_jan) %in% pages_to_filter_rep)]

# Extract page names of the first 1000 pages
page_names_republican_jan <- names(page_views_republican_filtered_jan)[1:100]
page_names_democrat_jan <- names(page_views_democrat_filtered_jan)[1:100]
```

```{r page_views_feb}
# Loop through all republican pages
page_views_republican_feb <- list()
for (i in republican_pages) {
  # Get page view data for the specified time frame
  page_views_republican_feb[[i]] <- page_view_month(i, "20210201", "20210228")
  if (is.na(page_views_republican_feb[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

# Loop through all democrat pages
page_views_democrat_feb <- list()
for (i in democrat_pages) {
  # Get page view data for the specified time frame
  page_views_democrat_feb[[i]] <- page_view_month(i, "20210201", "20210228")
  if (is.na(page_views_democrat_feb[[i]])) {
    # If page name could not be matched, print error message
    print(paste("Failed to fetch data for", i))
    next
  }
}

updated_rep_pv_list_feb <- list()
# Iterate through the list to standardise all page names
for (original_name in names(page_views_republican_feb)) {
  # Retrieve the value associated with the original name
  page_views_feb <- page_views_republican_feb[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_rep_pv_list_feb[[standardized_name]] <- page_views_feb
}

# Same for democratic pages
updated_dem_pv_list_feb <- list()
for (original_name in names(page_views_democrat_feb)) {
  # Retrieve the value associated with the original name
  page_views_feb <- page_views_democrat_feb[[original_name]]

  # Standardize the name
  standardized_name <- tolower(original_name)
  standardized_name <- gsub(" ", "_", standardized_name)
  standardized_name <- trimws(standardized_name)

  # Store the value under the new standardized name in the updated list
  updated_dem_pv_list_feb[[standardized_name]] <- page_views_feb
}

# Extract names from the network vertices
network_names_feb <- V(net_clickfeb21_filtered)$name

# Match the names of the network vertices with the page views
matched_names_rep_feb <- network_names_feb[
  network_names_feb %in% names(updated_rep_pv_list_feb)]
page_views_republican_filtered_feb <- updated_rep_pv_list_feb[matched_names_rep_feb]
matched_names_dem_feb <- network_names_feb[
  network_names_feb %in% names(updated_dem_pv_list_feb)]
page_views_democrat_filtered_feb <- updated_dem_pv_list_feb[matched_names_dem_feb]

# Order by descending page views
page_views_republican_filtered_feb <- page_views_republican_filtered_feb[order(
  unlist(page_views_republican_filtered_feb), decreasing = TRUE)]
page_views_democrat_filtered_feb <- page_views_democrat_filtered_feb[order(
  unlist(page_views_democrat_filtered_feb), decreasing = TRUE)]

# Filter out irrelevant pages
page_views_democrat_filtered_feb <- page_views_democrat_filtered_feb[
  !(names(page_views_democrat_filtered_feb) %in% pages_to_filter)]
page_views_republican_filtered_feb <- page_views_republican_filtered_feb[
  !(names(page_views_republican_filtered_feb) %in% pages_to_filter_rep)]

# Extract page names of the first 1000 pages
page_names_republican_feb <- names(page_views_republican_filtered_feb)[1:100]
page_names_democrat_feb <- names(page_views_democrat_filtered_feb)[1:100]
```

```{r pages_linking_to_opposite_party}
# Define a function to find nodes that have connections
# to the opposite party
find_nodes_with_opposing_neighbors <- function(network) {
  
  nodes_with_opposing_neighbors <- c()
  
  for (i in 1:length(V(network))) {
    
    current_party <- vertex_attr(network, name = "party")[i]
    neighbors_of_i <- neighbors(network, i)
    node_name <- V(network)$name[i]
    
    if (current_party == "Republican") {
      # Get the party of the neighbors
      neighbors_party <- vertex_attr(network, name = "party")[neighbors_of_i]
      # Check if any neighbor has a different party
      if ("Democrat" %in% neighbors_party) {
        # If Republican node with Democrat neighbors, 
        # add to list with nodes with opposing neighbors
        nodes_with_opposing_neighbors <- c(nodes_with_opposing_neighbors, node_name)
      }
    } else if (current_party == "Democrat") {
      # Get the party of the neighbors
      neighbors_party <- vertex_attr(network, name = "party")[neighbors_of_i]
      # Check if any neighbor has a different party
      if ("Republican" %in% neighbors_party) {
        nodes_with_opposing_neighbors <- c(nodes_with_opposing_neighbors, node_name)
      }
    }
  }
  
  return(nodes_with_opposing_neighbors)
}

# Find number of pages with links to the opposite party for all months
nodes_with_opposing_neighbors_sep <- find_nodes_with_opposing_neighbors(net_clicksep20_filtered)
nodes_with_opposing_neighbors_oct <- find_nodes_with_opposing_neighbors(net_clickoct20_filtered)
nodes_with_opposing_neighbors_nov <- find_nodes_with_opposing_neighbors(net_clicknov20_filtered)
nodes_with_opposing_neighbors_dec <- find_nodes_with_opposing_neighbors(net_clickdec20_filtered)
nodes_with_opposing_neighbors_jan <- find_nodes_with_opposing_neighbors(net_clickjan21_filtered)
nodes_with_opposing_neighbors_feb <- find_nodes_with_opposing_neighbors(net_clickfeb21_filtered)

# Perform intersections with the pages with
# the most page views for September
intersect_republican_sep <- intersect(
  nodes_with_opposing_neighbors_sep, page_names_republican_sep)
intersect_democrat_sep <- intersect(
  nodes_with_opposing_neighbors_sep, page_names_democrat_sep)
total_intersections_sep <- unique(c(intersect_republican_sep, intersect_democrat_sep))

# Same for October
intersect_republican_oct <- intersect(
  nodes_with_opposing_neighbors_oct, page_names_republican_oct)
intersect_democrat_oct <- intersect(
  nodes_with_opposing_neighbors_oct, page_names_democrat_oct)
total_intersections_oct <- unique(c(intersect_republican_oct, intersect_democrat_oct))

# Same for November
intersect_republican_nov <- intersect(
  nodes_with_opposing_neighbors_nov, page_names_republican)
intersect_democrat_nov <- intersect(
  nodes_with_opposing_neighbors_nov, page_names_democrat)
total_intersections_nov <- unique(c(intersect_republican_nov, intersect_democrat_nov))

# Same for December
intersect_republican_dec <- intersect(nodes_with_opposing_neighbors_dec, page_names_republican_dec)
intersect_democrat_dec <- intersect(nodes_with_opposing_neighbors_dec, page_names_democrat_dec)
total_intersections_dec <- unique(c(intersect_republican_dec, intersect_democrat_dec))

# Same for January
intersect_republican_jan <- intersect(nodes_with_opposing_neighbors_jan, page_names_republican_jan)
intersect_democrat_jan <- intersect(nodes_with_opposing_neighbors_jan, page_names_democrat_jan)
total_intersections_jan <- unique(c(intersect_republican_jan, intersect_democrat_jan))

# Same for February
intersect_republican_feb <- intersect(nodes_with_opposing_neighbors_feb, page_names_republican_feb)
intersect_democrat_feb <- intersect(nodes_with_opposing_neighbors_feb, page_names_democrat_feb)
total_intersections_feb <- unique(c(intersect_republican_feb, intersect_democrat_feb))

# Get the counts for each month
total_count_sep <- length(total_intersections_sep)
total_count_oct <- length(total_intersections_oct)
total_count_nov <- length(total_intersections_nov)
total_count_dec <- length(total_intersections_dec)
total_count_jan <- length(total_intersections_jan)
total_count_feb <- length(total_intersections_feb)


# Create a new object to store the results
result <- list(September = total_count_sep,
               October = total_count_oct,
               November = total_count_nov,
               December = total_count_dec,
               January = total_count_jan,
               February = total_count_feb)

# Create histogram
result_df <- data.frame(
  Month = factor(names(result), levels = c( "September", "October", "November", "December", "January", "February")),
  Count = unlist(result)
)

# Plot the results
ggplot(result_df, aes(x = Month, y = Count)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(
    title = "Figure B2. Number of Popular Pages with Neighbors of the Opposite Party",
    x = "Month",
    y = "Count of Pages"
  ) +
  theme(
    text = element_text(family = "Times New Roman"),  # Set all text to Times New Roman
    plot.title = element_text(hjust = 0.5, size = 25),  # Center the title and set the size
    axis.title = element_text(size = 20),  # Set axis titles size
    axis.text = element_text(size = 18)    # Set axis text size
  ) +
  theme(legend.position = "none")

```

```{r define_random_walk}
# Define a function to perform a random walk on the network
# while recording information about the nodes visited
random_party_walk <- function(graph, start, steps, weights, party_type, mode = "out", stuck = "return") {
  # Initialize the current node
  current_node <- start
  partition_switch <- FALSE
  n_steps <- 0
  
  current_node_index <- match(current_node, node_names)
  
  # Pre-fetch parties and names
  node_parties <- V(graph)$party
  node_names <- V(graph)$name
  edge_weights <- E(graph)$weight
  
  # Function to fetch weights in vectorized manner
  get_weights <- function(graph, current_node_index, neighbor_indices) {
    edge_ids <- sapply(neighbor_indices, function(neighbor_index) {
      get.edge.ids(graph, c(current_node_index, neighbor_index))
    })
    return(edge_weights[edge_ids])
  }

  # Perform the random walk
  for (i in 1:steps) {
    # Get neighbors of the current node based on the specified mode
    node_neighbors <- neighbors(graph, current_node, mode = mode)
    
    # If there are no neighbors, return or break depending on the "stuck" parameter
    if (length(node_neighbors) == 0) {
      if (n_steps == 0) { # if first node has no outgoing edges
        return(NA)
      }
      n_steps <- 15
      return(c(current_node, n_steps))
    }

    # Convert neighbors to names and indices
    node_neighbor_indices <- as.numeric(node_neighbors)
    
    # Fetch weights in vectorized manner
    current_node_index <- match(current_node, node_names)
    neighbor_weights <- get_weights(graph, current_node_index, node_neighbor_indices)
    
    
    # Calculate sum of edge weights
    sum_weights <- sum(neighbor_weights)
    
    # Normalize edge weights to obtain probabilities
    probabilities <- neighbor_weights / sum_weights
    
    # Sample a neighbor using the probabilities
    next_node_index <- sample(length(node_neighbors), 1, prob = probabilities)
    next_node <- node_neighbors[next_node_index]
    
    next_node_name <- as.character(node_names[next_node])
    
    # Update the current node
    current_node <- next_node_name
    
    n_steps <- n_steps + 1
    
    current_node_index <- match(current_node, node_names)
    
    if (party_type == "Democrat") {
      if (node_parties[current_node_index] == "Republican") {
        partition_switch <- TRUE
        break  # Stop the random walk if the current node is Republican
      }
    } else if (party_type == "Republican") {
      if (node_parties[current_node_index] == "Democrat") {
        partition_switch <- TRUE
        break  # Stop the random walk if the current node is Democrat
      }
    }
  }
  
  # If no partition switch occurred, set the number of steps to 20
  # for identification later
  if (partition_switch == FALSE) {
    n_steps <- 20
  }
  
  # Return the final node reached by the random walk
  return(c(current_node, n_steps))
}

# Define a function to run multiple random walks on the network
# returning descriptive statistics on the results
analyze_party_walk <- function(graph, party, vertices, steps = 10, iterations = 1) {
  
  # Initialise counters
  total_steps_needed <- vector()
  total_n_part_shift <- 0
  total_n_trapped <- 0
  total_n_republican <- 0
  total_n_democrat <- 0
  total_n_other <- 0
  
  # Initialize counters for the number of steps needed for a partition shift
  total_n_of_shift_steps_1 <- 0
  total_n_of_shift_steps_2 <- 0
  total_n_of_shift_steps_3 <- 0
  total_n_of_shift_steps_4 <- 0
  total_n_of_shift_steps_5 <- 0
  
  for (iter in 1:iterations) {
    # Initialise counters for current iteration
    n_trapped <- 0
    steps_needed <- vector(mode = "list", length = length(vertices))
    n_part_shift <- 0
    n_other <- 0
    n_republican <- 0
    n_democrat <- 0
    n_of_shift_steps_1 <- 0
    n_of_shift_steps_2 <- 0
    n_of_shift_steps_3 <- 0
    n_of_shift_steps_4 <- 0
    n_of_shift_steps_5 <- 0
    
    # Iterate through starting pages
    for (i in vertices) {
      cat("\rIteration:", iter, "Vertex:", i, flush = TRUE)
      start_node <- i
      
      output <- random_party_walk(
        graph, start_node, steps = steps, weights = E(graph)$weight, party_type = party, mode = "out", stuck = "return"
      )
      
      if (all(is.na(output))) {
        print("No outgoing edges")
        n_trapped <- n_trapped + 1
        next
      }
      
      # Extract output
      final_node <- output[1]
      steps_taken <- as.numeric(output[2])
      
      # If the random walk was trapped, increment the relevant counter
      if (steps_taken == 15) {
        n_trapped <- n_trapped + 1
        next
      }
      
      # Get the party of the final node
      final_node_index <- match(final_node, V(graph)$name)
      final_node_party <- V(graph)$party[final_node_index]
      
      # Increment the party counter relevant to the final node
      if (final_node_party == "Republican") {
        n_republican <- n_republican + 1
      } else if (final_node_party == "Democrat") {
        n_democrat <- n_democrat + 1
      } else {
        n_other <- n_other + 1
      }
      
      steps_needed[[i]] <- steps_taken
      
      # If party shift occurs, increment all relevant counters
      if (party == "Democrat" && final_node_party == "Republican") {
        n_part_shift <- n_part_shift + 1
        if (steps_taken == 1) n_of_shift_steps_1 <- n_of_shift_steps_1 + 1
        if (steps_taken == 2) n_of_shift_steps_2 <- n_of_shift_steps_2 + 1
        if (steps_taken == 3) n_of_shift_steps_3 <- n_of_shift_steps_3 + 1
        if (steps_taken == 4) n_of_shift_steps_4 <- n_of_shift_steps_4 + 1
        if (steps_taken == 5) n_of_shift_steps_5 <- n_of_shift_steps_5 + 1
      } else if (party == "Republican" && final_node_party == "Democrat") {
        n_part_shift <- n_part_shift + 1
        if (steps_taken == 1) n_of_shift_steps_1 <- n_of_shift_steps_1 + 1
        if (steps_taken == 2) n_of_shift_steps_2 <- n_of_shift_steps_2 + 1
        if (steps_taken == 3) n_of_shift_steps_3 <- n_of_shift_steps_3 + 1
        if (steps_taken == 4) n_of_shift_steps_4 <- n_of_shift_steps_4 + 1
        if (steps_taken == 5) n_of_shift_steps_5 <- n_of_shift_steps_5 + 1
      }
    }
    
    # Remove NULL, 15, and 20 values from steps_needed
    # 20 being walks which do not cross the party
    steps_needed <- steps_needed[!sapply(steps_needed, is.null)]
    steps_needed <- steps_needed[steps_needed != 15]
    steps_needed <- steps_needed[steps_needed != 20]
    
    # Get average steps needed to reach other party
    steps_needed <- unlist(steps_needed)
    mean_steps <- mean(steps_needed, na.rm = TRUE)
    
    # Aggregate results
    total_steps_needed <- c(total_steps_needed, steps_needed)
    total_n_part_shift <- total_n_part_shift + n_part_shift
    total_n_trapped <- total_n_trapped + n_trapped
    total_n_republican <- total_n_republican + n_republican
    total_n_democrat <- total_n_democrat + n_democrat
    total_n_other <- total_n_other + n_other
    
    # Aggregate step counts for partition shifts
    total_n_of_shift_steps_1 <- total_n_of_shift_steps_1 + n_of_shift_steps_1
    total_n_of_shift_steps_2 <- total_n_of_shift_steps_2 + n_of_shift_steps_2
    total_n_of_shift_steps_3 <- total_n_of_shift_steps_3 + n_of_shift_steps_3
    total_n_of_shift_steps_4 <- total_n_of_shift_steps_4 + n_of_shift_steps_4
    total_n_of_shift_steps_5 <- total_n_of_shift_steps_5 + n_of_shift_steps_5
  }
  
  # Calculate final averages
  final_mean_steps <- mean(total_steps_needed, na.rm = TRUE)
  
  return(list(
    steps = final_mean_steps, 
    n_part_shift = total_n_part_shift, 
    n_trapped = total_n_trapped, 
    n_republican = total_n_republican, 
    n_democrat = total_n_democrat, 
    n_other = total_n_other,
    n_of_shift_steps_1 = total_n_of_shift_steps_1,
    n_of_shift_steps_2 = total_n_of_shift_steps_2,
    n_of_shift_steps_3 = total_n_of_shift_steps_3,
    n_of_shift_steps_4 = total_n_of_shift_steps_4,
    n_of_shift_steps_5 = total_n_of_shift_steps_5
  ))
}
```

```{r run_random_walks}
# run random walks for September
results_dem_sep <- analyze_party_walk(
  net_clicksep20, "Democrat", page_names_democrat_sep, steps = 5, iterations = 50)

results_rep_sep <- analyze_party_walk(
  net_clicksep20, "Republican", page_names_republican_sep, steps = 5, iterations = 50)

# run random walks for October
results_dem_oct <- analyze_party_walk(
  net_clickoct20, "Democrat", page_names_democrat_oct, steps = 5, iterations = 50)

results_rep_oct <- analyze_party_walk(
  net_clickoct20, "Republican", page_names_republican_oct, steps = 5, iterations = 50)

# run random walks for November
results_dem_nov <- analyze_party_walk(
  net_clicknov20, "Democrat", page_names_democrat, steps = 5, iterations = 50)

results_rep_nov <- analyze_party_walk(
  net_clicknov20, "Republican", page_names_republican, steps = 5, iterations = 50)

# run random walks for December
results_dem_dec <- analyze_party_walk(
  net_clickdec20, "Democrat", page_names_democrat_dec, steps = 5, iterations = 50)

results_rep_dec <- analyze_party_walk(
  net_clickdec20, "Republican", page_names_republican_dec, steps = 5, iterations = 50)

# run random walks for January
results_dem_jan <- analyze_party_walk(
  net_clickjan21, "Democrat", page_names_democrat_jan, steps = 5, iterations = 50)

results_rep_jan <- analyze_party_walk(
  net_clickjan21, "Republican", page_names_republican_jan, steps = 5, iterations = 50)

# run random walks for February
results_dem_feb <- analyze_party_walk(
  net_clickfeb21, "Democrat", page_names_democrat_feb, steps = 5, iterations = 50)

results_rep_feb <- analyze_party_walk(
  net_clickfeb21, "Republican", page_names_republican_feb, steps = 5, iterations = 50)
```

```{r results_rw}
# Create data frame to aggregate results
results_rw <- data.frame(
  Month = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"),
  avg_steps_dem = c(results_dem_sep$steps, results_dem_oct$steps, results_dem_nov$steps, results_dem_dec$steps, results_dem_jan$steps, results_dem_feb$steps),
  avg_steps_rep = c(results_rep_sep$steps, results_rep_oct$steps, results_rep_nov$steps, results_rep_dec$steps, results_rep_jan$steps, results_rep_feb$steps),
  avg_shifts_dem = c(results_dem_sep$n_part_shift, results_dem_oct$n_part_shift, results_dem_nov$n_part_shift, results_dem_dec$n_part_shift, results_dem_jan$n_part_shift, results_dem_feb$n_part_shift),
  avg_shifts_rep = c(results_rep_sep$n_part_shift, results_rep_oct$n_part_shift, results_rep_nov$n_part_shift, results_rep_dec$n_part_shift, results_rep_jan$n_part_shift, results_rep_feb$n_part_shift)
)

results_rw
```


```{r create_random_nets_for_rw}
# Create random networks from the networks including "Other" pages
random_net_sep20_full <- sample_degseq(out.deg = degree(
  net_clicksep20, mode='out'), in.deg = degree(net_clicksep20, mode='in'), method = "simple")
random_net_oct20_full <- sample_degseq(out.deg = degree(
  net_clickoct20, mode='out'), in.deg = degree(net_clickoct20, mode='in'), method = "simple")
random_net_nov20_full <- sample_degseq(out.deg = degree(
  net_clicknov20, mode='out'), in.deg = degree(net_clicknov20, mode='in'), method = "simple")
random_net_dec20_full <- sample_degseq(out.deg = degree(
  net_clickdec20, mode='out'), in.deg = degree(net_clickdec20, mode='in'), method = "simple")
random_net_jan21_full <- sample_degseq(out.deg = degree(
  net_clickjan21, mode='out'), in.deg = degree(net_clickjan21, mode='in'), method = "simple")
random_net_feb21_full <- sample_degseq(out.deg = degree(
  net_clickfeb21, mode='out'), in.deg = degree(net_clickfeb21, mode='in'), method = "simple")

# Assign party attributes without calculating correlation
assign_attributes_and_calculate_correlation(random_net_sep20_full, net_clicksep20, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_net_oct20_full, net_clickoct20, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_net_nov20_full, net_clicknov20, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_net_dec20_full, net_clickdec20, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_net_jan21_full, net_clickjan21, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_net_feb21_full, net_clickfeb21, correlation = FALSE)
```


```{r rw_random_networks}
# Define function which runs random walks on random networks
random_walk_random_networks <- function(network) {
  num_nodes <- vcount(network)
  
  # Create node names since random walk function depends on node names
  random_names <- paste0("Node_", sample(1:num_nodes, num_nodes, replace = FALSE))
  V(network)$name <- random_names

  # Get pages with highest weighted degree
  degrees <- strength(network, weights = E(network)$weight)

  # Get party affiliations
  party_affiliations <- V(network)$party

  # Filter for Democratic nodes
  democratic_indices <- which(party_affiliations == "Democrat")
  democratic_degrees <- degrees[democratic_indices]

  # Order Democratic nodes by weighted degree and get top 100
  top_100_democratic_indices <- order(-democratic_degrees)[1:100]
  top_100_democratic_elements <- V(network)$name[democratic_indices[top_100_democratic_indices]]
  
  # Same for Republican nodes
  republican_indices <- which(party_affiliations == "Republican")
  republican_degrees <- degrees[republican_indices]
  top_100_republican_indices <- order(-republican_degrees)[1:100]
  top_100_republican_elements <- V(
    network)$name[republican_indices[top_100_republican_indices]]


  results_random_dem <- analyze_party_walk(network, "Democrat", top_100_democratic_elements, steps = 5, iterations = 50)
  
  results_random_rep <- analyze_party_walk(network, "Republican", top_100_republican_elements, steps = 5, iterations = 50)

  return(
    list(democrat = results_random_dem, republican = results_random_rep)
  )
}


# Run random walks on the random networks
results_random_sep20 <- random_walk_random_networks(random_net_sep20_full)
results_random_sep20_dem <- results_random_sep20[1]$democrat
results_random_sep20_rep <- results_random_sep20[2]$republican

results_random_oct20 <- random_walk_random_networks(random_net_oct20_full)
results_random_oct20_dem <- results_random_oct20[1]$democrat
results_random_oct20_rep <- results_random_oct20[2]$republican

results_random_nov20 <- random_walk_random_networks(random_net_nov20_full)
results_random_nov20_dem <- results_random_nov20[1]$democrat
results_random_nov20_rep <- results_random_nov20[2]$republican

results_random_dec20 <- random_walk_random_networks(random_net_dec20_full)
results_random_dec20_dem <- results_random_dec20[1]$democrat
results_random_dec20_rep <- results_random_dec20[2]$republican

results_random_jan21 <- random_walk_random_networks(random_net_jan21_full)
results_random_jan21_dem <- results_random_jan21[1]$democrat
results_random_jan21_rep <- results_random_jan21[2]$republican

results_random_feb21 <- random_walk_random_networks(random_net_feb21_full)
results_random_feb21_dem <- results_random_feb21[1]$democrat
results_random_feb21_rep <- results_random_feb21[2]$republican
```

```{r exposure_diversity}
# Define function which calculates exposure to diverse information
calculate_exposure <- function(results) {
  total_walks <- 5000 # 5000 walks per month per parry
  n_part_shift <- results$n_part_shift
  

  exposure <- n_part_shift / total_walks
  
  return(exposure)
}

# Calculate the exposure per month per party
exposure_dem_sep20 <- calculate_exposure(results_dem_sep)
exposure_rep_sep20 <- calculate_exposure(results_rep_sep)
exposure_dem_oct20 <- calculate_exposure(results_dem_oct)
exposure_rep_oct20 <- calculate_exposure(results_rep_oct)
exposure_dem_nov20 <- calculate_exposure(results_dem_nov)
exposure_rep_nov20 <- calculate_exposure(results_rep_nov)
exposure_dem_dec20 <- calculate_exposure(results_dem_dec)
exposure_rep_dec20 <- calculate_exposure(results_rep_dec)
exposure_dem_jan21 <- calculate_exposure(results_dem_jan)
exposure_rep_jan21 <- calculate_exposure(results_rep_jan)
exposure_dem_feb21 <- calculate_exposure(results_dem_feb)
exposure_rep_feb21 <- calculate_exposure(results_rep_feb)


exposure_data <- data.frame(
  month = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"),
  Democrat = c(exposure_dem_sep20, exposure_dem_oct20, exposure_dem_nov20, exposure_dem_dec20, exposure_dem_jan21, exposure_dem_feb21),
  Republican = c(exposure_rep_sep20, exposure_rep_oct20, exposure_rep_nov20, exposure_rep_dec20, exposure_rep_jan21, exposure_rep_feb21)
)

# Prepare data frame for plotting
exposure_data$month <- factor(exposure_data$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))
exposure_data_long <- pivot_longer(exposure_data, cols = c(Democrat, Republican), names_to = "variable", values_to = "value")

custom_colors <- c("Democrat" = "dodgerblue", "Republican" = "red")

# Plot the results
ggplot(exposure_data_long, aes(x = month, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Figure 4. Exposure to Diverse Information",
    x = "Month",
    y = "Exposure to Diverse Information",
    fill = "Party of Starting Node"
  ) +
  scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(hjust = 0.5, size = 25),
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15),
    legend.text = element_text(size = 15, color = "black"),
    legend.title = element_text(size = 20, color = "black")
  )
```

```{r exposure_by_steps}
# Define the function to calculate exposure percentage for each step
calculate_exposure_percentage <- function(results) {
  total_walks <- 5000
  
  # Get the number of shifts for each step
  shift_steps <- c(results$n_of_shift_steps_1, results$n_of_shift_steps_2,
                   results$n_of_shift_steps_3, results$n_of_shift_steps_4,
                   results$n_of_shift_steps_5)
  
  # Calculate the cumulative number of shifts and exposure percentages
  cumulative_shifts <- cumsum(shift_steps)
  exposure_percentage <- (cumulative_shifts / total_walks) * 100
  
  return(exposure_percentage)
}

# Calculate the exposure percentages for each month and party
exposure_percentages_sep <- list(
  democrat = calculate_exposure_percentage(results_dem_sep),
  republican = calculate_exposure_percentage(results_rep_sep)
)

exposure_percentages_oct <- list(
  democrat = calculate_exposure_percentage(results_dem_oct),
  republican = calculate_exposure_percentage(results_rep_oct)
)

exposure_percentages_nov <- list(
  democrat = calculate_exposure_percentage(results_dem_nov),
  republican = calculate_exposure_percentage(results_rep_nov)
)

exposure_percentages_dec <- list(
  democrat = calculate_exposure_percentage(results_dem_dec),
  republican = calculate_exposure_percentage(results_rep_dec)
)

exposure_percentages_jan <- list(
  democrat = calculate_exposure_percentage(results_dem_jan),
  republican = calculate_exposure_percentage(results_rep_jan)
)

exposure_percentages_feb <- list(
  democrat = calculate_exposure_percentage(results_dem_feb),
  republican = calculate_exposure_percentage(results_rep_feb)
)

# Function to calculate the average exposure percentage for each step
average_exposure <- function(dem_exp, rep_exp) {
  return((dem_exp + rep_exp) / 2)
}

# Create the final combined data frame with averaged exposure percentages
combine_and_average_steps <- function(month, dem_exp, rep_exp) {
  avg_exposure <- average_exposure(dem_exp, rep_exp)
  data.frame(
    month = rep(month, 5), 
    steps = 1:5, 
    exposure = avg_exposure
  )
}

# Combine and average the exposure percentages for all months
exposure_df <- bind_rows(
  combine_and_average_steps("September 2020",
                            exposure_percentages_sep$democrat, exposure_percentages_sep$republican),
  combine_and_average_steps("October 2020",
                            exposure_percentages_oct$democrat, exposure_percentages_oct$republican),
  combine_and_average_steps("November 2020",
                            exposure_percentages_nov$democrat, exposure_percentages_nov$republican),
  combine_and_average_steps("December 2020",
                            exposure_percentages_dec$democrat, exposure_percentages_dec$republican),
  combine_and_average_steps("January 2021",
                            exposure_percentages_jan$democrat, exposure_percentages_jan$republican),
  combine_and_average_steps("February 2021",
                            exposure_percentages_feb$democrat, exposure_percentages_feb$republican)
)

# Factorise month
exposure_df$month <- factor(exposure_df$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

# Plot the results
ggplot(exposure_df, aes(x = steps, y = exposure, color = month, group = month)) +
  geom_line() +
  geom_point(size = 1) +
  labs(
    title = "Figure 6. Exposure to Diverse Information By Number of Steps",
    x = "Number of Steps",
    y = "% of Walks Exposed to Other Partition",
    color = "Month"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(hjust = 0.5, size = 25), 
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 20)
  )
```



```{r exposure_random_networks}
# Calculate exposure for random networks
exposure_random_sep20 <- calculate_exposure(results_random_sep20_dem)
exposure_random_sep20_rep <- calculate_exposure(results_random_sep20_rep)
exposure_random_oct20 <- calculate_exposure(results_random_oct20_dem)
exposure_random_oct20_rep <- calculate_exposure(results_random_oct20_rep)
exposure_random_nov20 <- calculate_exposure(results_random_nov20_dem)
exposure_random_nov20_rep <- calculate_exposure(results_random_nov20_rep)
exposure_random_dec20 <- calculate_exposure(results_random_dec20_dem)
exposure_random_dec20_rep <- calculate_exposure(results_random_dec20_rep)
exposure_random_jan21 <- calculate_exposure(results_random_jan21_dem)
exposure_random_jan21_rep <- calculate_exposure(results_random_jan21_rep)
exposure_random_feb21 <- calculate_exposure(results_random_feb21_dem)
exposure_random_feb21_rep <- calculate_exposure(results_random_feb21_rep)


exposure_random_data <- data.frame(
  month = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"),
  Democrat = c(exposure_random_sep20, exposure_random_oct20, exposure_random_nov20, exposure_random_dec20, exposure_random_jan21, exposure_random_feb21),
  Republican = c(exposure_random_sep20_rep, exposure_random_oct20_rep, exposure_random_nov20_rep, exposure_random_dec20_rep, exposure_random_jan21_rep, exposure_random_feb21_rep)
)

# Factorise month
exposure_random_data$month <- factor(exposure_random_data$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

# Prepare data frame for plotting
exposure_random_data_long <- pivot_longer(exposure_random_data, cols = c(Democrat, Republican), names_to = "variable", values_to = "value")
exposure_random_data_long$variable <- factor(exposure_random_data_long$variable, levels = c("Democrat", "Republican"))


custom_colors <- c("Democrat" = "dodgerblue", "Republican" = "red")

# Plot the results
ggplot(exposure_random_data_long, aes(x = month, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Figure 5. Exposure to Diverse Information in Random Networks",
    x = "Month",
    y = "Exposure to Diverse Information",
    fill = "Party of Starting Node"
  ) +
  scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),  # Set all text to Times New Roman
    plot.title = element_text(hjust = 0.5, size = 25),  # Center the plot title and set size
    axis.title = element_text(size = 20),  # Set size for axis titles
    axis.text = element_text(size = 15),  # Set size for axis text
    legend.text = element_text(size = 15, color = "black"),  # Set size and color for legend text
    legend.title = element_text(size = 20, color = "black")  # Set size and color for legend title
  )

```


```{r exposure_by_step_random}
# Define the exposure percentages for each month and party
exposure_percentages_random_sep <- list(
  democrat = calculate_exposure_percentage(results_random_sep20_dem),
  republican = calculate_exposure_percentage(results_random_sep20_rep)
)

exposure_percentages_random_oct <- list(
  democrat = calculate_exposure_percentage(results_random_oct20_dem),
  republican = calculate_exposure_percentage(results_random_oct20_rep)
)

exposure_percentages_random_nov <- list(
  democrat = calculate_exposure_percentage(results_random_nov20_dem),
  republican = calculate_exposure_percentage(results_random_nov20_rep)
)

exposure_percentages_random_dec <- list(
  democrat = calculate_exposure_percentage(results_random_dec20_dem),
  republican = calculate_exposure_percentage(results_random_dec20_rep)
)

exposure_percentages_random_jan <- list(
  democrat = calculate_exposure_percentage(results_random_jan21_dem),
  republican = calculate_exposure_percentage(results_random_jan21_rep)
)

exposure_percentages_random_feb <- list(
  democrat = calculate_exposure_percentage(results_random_feb21_dem),
  republican = calculate_exposure_percentage(results_random_feb21_rep)
)


# Combine and average the exposure percentages for all months
exposure_random_df <- bind_rows(
  combine_and_average_steps(
    "September 2020", exposure_percentages_random_sep$democrat, exposure_percentages_random_sep$republican),
  combine_and_average_steps(
    "October 2020", exposure_percentages_random_oct$democrat, exposure_percentages_random_oct$republican),
  combine_and_average_steps(
    "November 2020", exposure_percentages_random_nov$democrat, exposure_percentages_random_nov$republican),
  combine_and_average_steps(
    "December 2020", exposure_percentages_random_dec$democrat, exposure_percentages_random_dec$republican),
  combine_and_average_steps(
    "January 2021", exposure_percentages_random_jan$democrat, exposure_percentages_random_jan$republican),
  combine_and_average_steps(
    "February 2021", exposure_percentages_random_feb$democrat, exposure_percentages_random_feb$republican)
)

# Factorise month
exposure_random_df$month <- factor(exposure_random_df$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

# Plot the results
ggplot(exposure_random_df, aes(x = steps, y = exposure, color = month, group = month)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Figure 7. Exposure to Diverse Information By Number of Steps in Random Networks",
    x = "Number of Steps",
    y = "% of Walks Exposed to Other Partition",
    color = "Month"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(hjust = 0.5, size = 25), 
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 20)
  )
```


```{r create_robustness_networks}
# Define function which removes 200 "Republican" nodes at random
create_net_robust <- function(full_network) {

  republican_nodes <- V(full_network)[party == "Republican"]
  
  # Randomly select 200 nodes to remove
  nodes_to_remove <- sample(republican_nodes, size = 200, replace = FALSE)
  
  # Remove the selected nodes from the network
  robust_network <- delete_vertices(full_network, nodes_to_remove)
  
  return(robust_network)
}

# Remove 200 Republican nodes from each network
robust_net_nov19 <- create_net_robust(net_clicknov19_filtered)
robust_net_dec19 <- create_net_robust(net_clickdec19_filtered)
robust_net_jan20 <- create_net_robust(net_clickjan20_filtered)
robust_net_feb20 <- create_net_robust(net_clickfeb20_filtered)
robust_net_mar20 <- create_net_robust(net_clickmar20_filtered)
robust_net_apr20 <- create_net_robust(net_clickapr20_filtered)
robust_net_may20 <- create_net_robust(net_clickmay20_filtered)
robust_net_jun20 <- create_net_robust(net_clickjun20_filtered)
robust_net_jul20 <- create_net_robust(net_clickjul20_filtered)
robust_net_aug20 <- create_net_robust(net_clickaug20_filtered)
robust_net_sep20 <- create_net_robust(net_clicksep20_filtered)
robust_net_oct20 <- create_net_robust(net_clickoct20_filtered)
robust_net_nov20 <- create_net_robust(net_clicknov20_filtered)
robust_net_dec20 <- create_net_robust(net_clickdec20_filtered)
robust_net_jan21 <- create_net_robust(net_clickjan21_filtered)
robust_net_feb21 <- create_net_robust(net_clickfeb21_filtered)
robust_net_mar21 <- create_net_robust(net_clickmar21_filtered)
robust_net_apr21 <- create_net_robust(net_clickapr21_filtered)
robust_net_may21 <- create_net_robust(net_clickmay21_filtered)
robust_net_jun21 <- create_net_robust(net_clickjun21_filtered)
robust_net_jul21 <- create_net_robust(net_clickjul21_filtered)
robust_net_aug21 <- create_net_robust(net_clickaug21_filtered)
robust_net_sep21 <- create_net_robust(net_clicksep21_filtered)
robust_net_oct21 <- create_net_robust(net_clickoct21_filtered)
robust_net_nov21 <- create_net_robust(net_clicknov21_filtered)
```

```{r edgecount_robustness}
# Create mixing matrices for robust networks
mixing_matrix_robust_nov19 <- mixingm(robust_net_nov19, "party")
mixing_matrix_robust_dec19 <- mixingm(robust_net_dec19, "party")
mixing_matrix_robust_jan20 <- mixingm(robust_net_jan20, "party")
mixing_matrix_robust_feb20 <- mixingm(robust_net_feb20, "party")
mixing_matrix_robust_mar20 <- mixingm(robust_net_mar20, "party")
mixing_matrix_robust_apr20 <- mixingm(robust_net_apr20, "party")
mixing_matrix_robust_may20 <- mixingm(robust_net_may20, "party")
mixing_matrix_robust_jun20 <- mixingm(robust_net_jun20, "party")
mixing_matrix_robust_jul20 <- mixingm(robust_net_jul20, "party")
mixing_matrix_robust_aug20 <- mixingm(robust_net_aug20, "party")
mixing_matrix_robust_sep20 <- mixingm(robust_net_sep20, "party")
mixing_matrix_robust_oct20 <- mixingm(robust_net_oct20, "party")
mixing_matrix_robust_nov20 <- mixingm(robust_net_nov20, "party")
mixing_matrix_robust_dec20 <- mixingm(robust_net_dec20, "party")
mixing_matrix_robust_jan21 <- mixingm(robust_net_jan21, "party")
mixing_matrix_robust_feb21 <- mixingm(robust_net_feb21, "party")
mixing_matrix_robust_mar21 <- mixingm(robust_net_mar21, "party")
mixing_matrix_robust_apr21 <- mixingm(robust_net_apr21, "party")
mixing_matrix_robust_may21 <- mixingm(robust_net_may21, "party")
mixing_matrix_robust_jun21 <- mixingm(robust_net_jun21, "party")
mixing_matrix_robust_jul21 <- mixingm(robust_net_jul21, "party")
mixing_matrix_robust_aug21 <- mixingm(robust_net_aug21, "party")
mixing_matrix_robust_sep21 <- mixingm(robust_net_sep21, "party")
mixing_matrix_robust_oct21 <- mixingm(robust_net_oct21, "party")
mixing_matrix_robust_nov21 <- mixingm(robust_net_nov21, "party")

# Collect data in a list
robust_matrices_list <- list(
  November_19 = mixing_matrix_robust_nov19, December_19 = mixing_matrix_robust_dec19,
  January_20 = mixing_matrix_robust_jan20, February_20 = mixing_matrix_robust_feb20, March_20 = mixing_matrix_robust_mar20,
  April_20 = mixing_matrix_robust_apr20, May_20 = mixing_matrix_robust_may20, June_20 = mixing_matrix_robust_jun20,
  July_20 = mixing_matrix_robust_jul20, August_20 = mixing_matrix_robust_aug20, September_20 = mixing_matrix_robust_sep20,
  October_20 = mixing_matrix_robust_oct20, November_20 = mixing_matrix_robust_nov20, December_20 = mixing_matrix_robust_dec20,
  January_21 = mixing_matrix_robust_jan21, February_21 = mixing_matrix_robust_feb21, March_21 = mixing_matrix_robust_mar21,
  April_21 = mixing_matrix_robust_apr21, May_21 = mixing_matrix_robust_may21, June_21 = mixing_matrix_robust_jun21,
  July_21 = mixing_matrix_robust_jul21, August_21 = mixing_matrix_robust_aug21, September_21 = mixing_matrix_robust_sep21,
  October_21 = mixing_matrix_robust_oct21, November_21 = mixing_matrix_robust_nov21
)


# Apply the edge counts function from the initial analysis
results <- bind_rows(lapply(names(robust_matrices_list), function(month) {
  extract_counts(robust_matrices_list[[month]], month)
}))

# Prepare data for plotting
results$Month <- factor(results$Month, levels = c(
  "November_19", "December_19", "January_20", "February_20", "March_20", "April_20", "May_20", "June_20",
  "July_20", "August_20", "September_20", "October_20", "November_20", "December_20",
  "January_21", "February_21", "March_21", "April_21", "May_21", "June_21", "July_21", "August_21",
  "September_21", "October_21", "November_21"
))
results_long <- results %>%
  gather(key = "Interaction", value = "Count", -Month)
results_long$Interaction <- factor(results_long$Interaction, levels = c(
  "Democrat.to.Democrat", "Democrat.to.Republican", "Republican.to.Democrat", "Republican.to.Republican"
))
y_breaks <- pretty(results_long$Count, n = 5)
custom_labels <- c(
  "November '19", "December '19", "January '20", "February '20", "March '20", "April '20", "May '20", "June '20",
  "July '20", "August '20", "September '20", "October '20", "November '20", "December '20",
  "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21",
  "September '21", "October '21", "November '21"
)
custom_legend_labels <- c("Democrat to Democrat", "Democrat to Republican", "Republican to Democrat", "Republican to Republican")
custom_colors <- c(
  "Democrat.to.Democrat" = "dodgerblue", 
  "Republican.to.Democrat" = "pink", 
  "Democrat.to.Republican" = "purple", 
  "Republican.to.Republican" = "red"
)

# Plot the results
ggplot(results_long, aes(x = Month, y = Count, color = Interaction, group = Interaction)) +
  geom_line() +
  geom_point(size = 1) +
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.5) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.5) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = 0.5, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -2, color = "black", family = "Times New Roman", size = 6) +
  labs(title = "Figure C1. Count of Edges for Networks with Equal Pages per Party",
       x = "Month",
       y = "Edge Count", 
       color = "Link Type") +
  scale_x_discrete(labels = custom_labels) +
  scale_y_continuous(breaks = y_breaks) +
  scale_color_manual(values = custom_colors, labels = custom_legend_labels) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 15, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    plot.title = element_text(size = 25, family = "Times New Roman", hjust = 0.5),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    legend.text = element_text(size = 15, family = "Times New Roman"),
    legend.title = element_text(size = 20, family = "Times New Roman")
  )
```

```{r robustness_modularity}
# Calculate modularity for each robust network version
modularity_scores_robust <- data.frame(
  Month = c(
    "November '19", "December '19", "January '20", "February '20", "March '20", "April '20", "May '20", "June '20",
    "July '20", "August '20", "September '20", "October '20", "November '20", "December '20",
    "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21",
    "September '21", "October '21", "November '21"
  ),
  Modularity = c(
    calculate_modularity(robust_net_nov19),
    calculate_modularity(robust_net_dec19),
    calculate_modularity(robust_net_jan20),
    calculate_modularity(robust_net_feb20),
    calculate_modularity(robust_net_mar20),
    calculate_modularity(robust_net_apr20),
    calculate_modularity(robust_net_may20),
    calculate_modularity(robust_net_jun20),
    calculate_modularity(robust_net_jul20),
    calculate_modularity(robust_net_aug20),
    calculate_modularity(robust_net_sep20),
    calculate_modularity(robust_net_oct20),
    calculate_modularity(robust_net_nov20),
    calculate_modularity(robust_net_dec20),
    calculate_modularity(robust_net_jan21),
    calculate_modularity(robust_net_feb21),
    calculate_modularity(robust_net_mar21),
    calculate_modularity(robust_net_apr21),
    calculate_modularity(robust_net_may21),
    calculate_modularity(robust_net_jun21),
    calculate_modularity(robust_net_jul21),
    calculate_modularity(robust_net_aug21), 
    calculate_modularity(robust_net_sep21), 
    calculate_modularity(robust_net_oct21),
    calculate_modularity(robust_net_nov21)
  )
)


modularity_scores_robust$Month <- factor(modularity_scores_robust$Month, levels = modularity_scores_robust$Month)

average_modularit_robust <- mean(modularity_scores_robust$Modularity, na.rm = TRUE)

# Plot the modularity scores
ggplot(modularity_scores_robust, aes(x = Month, y = Modularity)) +
  geom_point(size = 0.8, color = "purple") +  # Add points
  geom_line(aes(group = 1), color = "purple") +  # Connect points with lines
  geom_hline(yintercept = average_modularit_robust, linetype = "solid", color = "darkorange3", alpha = 0.6) + 
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.5) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.5) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = 0, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -2, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = Inf, y = average_modularity, label = "Average Modularity", vjust = 1.5, hjust = 1, color = "darkorange3", family = "Times New Roman", size = 5) +
  labs(x = "Month", y = "Modularity", title = "Figure C2. Modularity Scores for Networks with Equal Pages per Party") +
  theme_minimal() +  # Minimal theme
  theme(
    axis.text.x = element_text(size = 15, angle = 45, hjust = 1, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    plot.title = element_text(size = 25, family = "Times New Roman", hjust = 0.5),
    legend.text = element_text(family = "Times New Roman"),
    legend.title = element_text(family = "Times New Roman")
  ) +
  scale_y_continuous(limits = c(0, 0.4))
```

```{r robustness_boundary_polarisation}
# Calculate boundary polarisation for each robust network version
bp_robust_nov19 <- calculate_spearman_correlation(robust_net_nov19)
bp_robust_dec19 <- calculate_spearman_correlation(robust_net_dec19)
bp_robust_jan20 <- calculate_spearman_correlation(robust_net_jan20)
bp_robust_feb20 <- calculate_spearman_correlation(robust_net_feb20)
bp_robust_mar20 <- calculate_spearman_correlation(robust_net_mar20)
bp_robust_apr20 <- calculate_spearman_correlation(robust_net_apr20)
bp_robust_may20 <- calculate_spearman_correlation(robust_net_may20)
bp_robust_jun20 <- calculate_spearman_correlation(robust_net_jun20)
bp_robust_jul20 <- calculate_spearman_correlation(robust_net_jul20)
bp_robust_aug20 <- calculate_spearman_correlation(robust_net_aug20)
bp_robust_sep20 <- calculate_spearman_correlation(robust_net_sep20)
bp_robust_oct20 <- calculate_spearman_correlation(robust_net_oct20)
bp_robust_nov20 <- calculate_spearman_correlation(robust_net_nov20)
bp_robust_dec20 <- calculate_spearman_correlation(robust_net_dec20)
bp_robust_jan21 <- calculate_spearman_correlation(robust_net_jan21)
bp_robust_feb21 <- calculate_spearman_correlation(robust_net_feb21)
bp_robust_mar21 <- calculate_spearman_correlation(robust_net_mar21)
bp_robust_apr21 <- calculate_spearman_correlation(robust_net_apr21)
bp_robust_may21 <- calculate_spearman_correlation(robust_net_may21)
bp_robust_jun21 <- calculate_spearman_correlation(robust_net_jun21)
bp_robust_jul21 <- calculate_spearman_correlation(robust_net_jul21)
bp_robust_aug21 <- calculate_spearman_correlation(robust_net_aug21)
bp_robust_sep21 <- calculate_spearman_correlation(robust_net_sep21)
bp_robust_oct21 <- calculate_spearman_correlation(robust_net_oct21)
bp_robust_nov21 <- calculate_spearman_correlation(robust_net_nov21)

# create random networks for robustness check of boundary polarisation
random_robust_net_nov19 <- sample_degseq(out.deg = degree(
  robust_net_nov19, mode='out'), in.deg = degree(
    robust_net_nov19, mode='in'), method = "simple")
random_robust_net_dec19 <- sample_degseq(out.deg = degree(
  robust_net_dec19, mode='out'), in.deg = degree(
    robust_net_dec19, mode='in'), method = "simple")
random_robust_net_jan20 <- sample_degseq(out.deg = degree(
  robust_net_jan20, mode='out'), in.deg = degree(
    robust_net_jan20, mode='in'), method = "simple")
random_robust_net_feb20 <- sample_degseq(out.deg = degree(
  robust_net_feb20, mode='out'), in.deg = degree(
    robust_net_feb20, mode='in'), method = "simple")
random_robust_net_mar20 <- sample_degseq(out.deg = degree(
  robust_net_mar20, mode='out'), in.deg = degree(
    robust_net_mar20, mode='in'), method = "simple")
random_robust_net_apr20 <- sample_degseq(out.deg = degree(
  robust_net_apr20, mode='out'), in.deg = degree(
    robust_net_apr20, mode='in'), method = "simple")
random_robust_net_may20 <- sample_degseq(out.deg = degree(
  robust_net_may20, mode='out'), in.deg = degree(
    robust_net_may20, mode='in'), method = "simple")
random_robust_net_jun20 <- sample_degseq(out.deg = degree(
  robust_net_jun20, mode='out'), in.deg = degree(
    robust_net_jun20, mode='in'), method = "simple")
random_robust_net_jul20 <- sample_degseq(out.deg = degree(
  robust_net_jul20, mode='out'), in.deg = degree(
    robust_net_jul20, mode='in'), method = "simple")
random_robust_net_aug20 <- sample_degseq(out.deg = degree(
  robust_net_aug20, mode='out'), in.deg = degree(
    robust_net_aug20, mode='in'), method = "simple")
random_robust_net_sep20 <- sample_degseq(out.deg = degree(
  robust_net_sep20, mode='out'), in.deg = degree(
    robust_net_sep20, mode='in'), method = "simple")
random_robust_net_oct20 <- sample_degseq(out.deg = degree(
  robust_net_oct20, mode='out'), in.deg = degree(
    robust_net_oct20, mode='in'), method = "simple")
random_robust_net_nov20 <- sample_degseq(out.deg = degree(
  robust_net_nov20, mode='out'), in.deg = degree(
    robust_net_nov20, mode='in'), method = "simple")
random_robust_net_dec20 <- sample_degseq(out.deg = degree(
  robust_net_dec20, mode='out'), in.deg = degree(
    robust_net_dec20, mode='in'), method = "simple")
random_robust_net_jan21 <- sample_degseq(out.deg = degree(
  robust_net_jan21, mode='out'), in.deg = degree(
    robust_net_jan21, mode='in'), method = "simple")
random_robust_net_feb21 <- sample_degseq(out.deg = degree(
  robust_net_feb21, mode='out'), in.deg = degree(
    robust_net_feb21, mode='in'), method = "simple")
random_robust_net_mar21 <- sample_degseq(out.deg = degree(
  robust_net_mar21, mode='out'), in.deg = degree(
    robust_net_mar21, mode='in'), method = "simple")
random_robust_net_apr21 <- sample_degseq(out.deg = degree(
  robust_net_apr21, mode='out'), in.deg = degree(
    robust_net_apr21, mode='in'), method = "simple")
random_robust_net_may21 <- sample_degseq(out.deg = degree(
  robust_net_may21, mode='out'), in.deg = degree(
    robust_net_may21, mode='in'), method = "simple")
random_robust_net_jun21 <- sample_degseq(out.deg = degree(
  robust_net_jun21, mode='out'), in.deg = degree(
    robust_net_jun21, mode='in'), method = "simple")
random_robust_net_jul21 <- sample_degseq(out.deg = degree(
  robust_net_jul21, mode='out'), in.deg = degree(
    robust_net_jul21, mode='in'), method = "simple")
random_robust_net_aug21 <- sample_degseq(out.deg = degree(
  robust_net_aug21, mode='out'), in.deg = degree(
    robust_net_aug21, mode='in'), method = "simple")
random_robust_net_sep21 <- sample_degseq(out.deg = degree(
  robust_net_sep21, mode='out'), in.deg = degree(
    robust_net_sep21, mode='in'), method = "simple")
random_robust_net_oct21 <- sample_degseq(out.deg = degree(
  robust_net_oct21, mode='out'), in.deg = degree(
    robust_net_oct21, mode='in'), method = "simple")
random_robust_net_nov21 <- sample_degseq(out.deg = degree(
  robust_net_nov21, mode='out'), in.deg = degree(
    robust_net_nov21, mode='in'), method = "simple")

# Assign party and weight attributes and calculate correlation
bp_random_robust_nov19 <- assign_attributes_and_calculate_correlation(random_robust_net_nov19, robust_net_nov19)
bp_random_robust_dec19 <- assign_attributes_and_calculate_correlation(random_robust_net_dec19, robust_net_dec19)
bp_random_robust_jan20 <- assign_attributes_and_calculate_correlation(random_robust_net_jan20, robust_net_jan20)
bp_random_robust_feb20 <- assign_attributes_and_calculate_correlation(random_robust_net_feb20, robust_net_feb20)
bp_random_robust_mar20 <- assign_attributes_and_calculate_correlation(random_robust_net_mar20, robust_net_mar20)
bp_random_robust_apr20 <- assign_attributes_and_calculate_correlation(random_robust_net_apr20, robust_net_apr20)
bp_random_robust_may20 <- assign_attributes_and_calculate_correlation(random_robust_net_may20, robust_net_may20)
bp_random_robust_jun20 <- assign_attributes_and_calculate_correlation(random_robust_net_jun20, robust_net_jun20)
bp_random_robust_jul20 <- assign_attributes_and_calculate_correlation(random_robust_net_jul20, robust_net_jul20)
bp_random_robust_aug20 <- assign_attributes_and_calculate_correlation(random_robust_net_aug20, robust_net_aug20)
bp_random_robust_sep20 <- assign_attributes_and_calculate_correlation(random_robust_net_sep20, robust_net_sep20)
bp_random_robust_oct20 <- assign_attributes_and_calculate_correlation(random_robust_net_oct20, robust_net_oct20)
bp_random_robust_nov20 <- assign_attributes_and_calculate_correlation(random_robust_net_nov20, robust_net_nov20)
bp_random_robust_dec20 <- assign_attributes_and_calculate_correlation(random_robust_net_dec20, robust_net_dec20)
bp_random_robust_jan21 <- assign_attributes_and_calculate_correlation(random_robust_net_jan21, robust_net_jan21)
bp_random_robust_feb21 <- assign_attributes_and_calculate_correlation(random_robust_net_feb21, robust_net_feb21)
bp_random_robust_mar21 <- assign_attributes_and_calculate_correlation(random_robust_net_mar21, robust_net_mar21)
bp_random_robust_apr21 <- assign_attributes_and_calculate_correlation(random_robust_net_apr21, robust_net_apr21)
bp_random_robust_may21 <- assign_attributes_and_calculate_correlation(random_robust_net_may21, robust_net_may21)
bp_random_robust_jun21 <- assign_attributes_and_calculate_correlation(random_robust_net_jun21, robust_net_jun21)
bp_random_robust_jul21 <- assign_attributes_and_calculate_correlation(random_robust_net_jul21, robust_net_jul21)
bp_random_robust_aug21 <- assign_attributes_and_calculate_correlation(random_robust_net_aug21, robust_net_aug21)
bp_random_robust_sep21 <- assign_attributes_and_calculate_correlation(random_robust_net_sep21, robust_net_sep21)
bp_random_robust_oct21 <- assign_attributes_and_calculate_correlation(random_robust_net_oct21, robust_net_oct21)
bp_random_robust_nov21 <- assign_attributes_and_calculate_correlation(random_robust_net_nov21, robust_net_nov21)

# Collect boundary polarisation scores in data frame
boundary_polarisation_scores <- data.frame(
  Month = c(
    "November '19", "December '19", "January '20", "February '20", "March '20", "April '20", "May '20", "June '20", "July '20", "August '20", "September '20", "October '20", "November '20", "December '20", "January '21", "February '21", "March '21", "April '21", "May '21", "June '21", "July '21", "August '21", "September '21", "October '21", "November '21"),
  Boundary_Polarisation = c(
    bp_robust_nov19[1]$overall, bp_robust_dec19[1]$overall, bp_robust_jan20[1]$overall, bp_robust_feb20[1]$overall, bp_robust_mar20[1]$overall, bp_robust_apr20[1]$overall, bp_robust_may20[1]$overall, bp_robust_jun20[1]$overall, bp_robust_jul20[1]$overall, bp_robust_aug20[1]$overall, bp_robust_sep20[1]$overall, bp_robust_oct20[1]$overall, bp_robust_nov20[1]$overall, bp_robust_dec20[1]$overall, bp_robust_jan21[1]$overall, bp_robust_feb21[1]$overall, bp_robust_mar21[1]$overall, bp_robust_apr21[1]$overall, bp_robust_may21[1]$overall, bp_robust_jun21[1]$overall, bp_robust_jul21[1]$overall, bp_robust_aug21[1]$overall, bp_robust_sep21[1]$overall, bp_robust_oct21[1]$overall, bp_robust_nov21[1]$overall
  ),
  Random_Polarisation = c(
    bp_random_robust_nov19[1]$overall, bp_random_robust_dec19[1]$overall, bp_random_robust_jan20[1]$overall, bp_random_robust_feb20[1]$overall, bp_random_robust_mar20[1]$overall, bp_random_robust_apr20[1]$overall, bp_random_robust_may20[1]$overall, bp_random_robust_jun20[1]$overall, bp_random_robust_jul20[1]$overall, bp_random_robust_aug20[1]$overall, bp_random_robust_sep20[1]$overall, bp_random_robust_oct20[1]$overall, bp_random_robust_nov20[1]$overall, bp_random_robust_dec20[1]$overall, bp_random_robust_jan21[1]$overall, bp_random_robust_feb21[1]$overall, bp_random_robust_mar21[1]$overall, bp_random_robust_apr21[1]$overall, bp_random_robust_may21[1]$overall, bp_random_robust_jun21[1]$overall, bp_random_robust_jul21[1]$overall, bp_random_robust_aug21[1]$overall, bp_random_robust_sep21[1]$overall, bp_random_robust_oct21[1]$overall, bp_random_robust_nov21[1]$overall
  )
  )

boundary_polarisation_scores$Month <- factor(boundary_polarisation_scores$Month, levels = boundary_polarisation_scores$Month)


custom_colors <- c("Random Networks" = "darkorange", "Empirical Networks" = "purple")

# Plot the results
ggplot(boundary_polarisation_scores, aes(x = Month)) +
  # Plot points and lines for Empirical Networks
  geom_point(aes(y = Boundary_Polarisation, color = "Empirical Networks"), size = 0.8) +  
  geom_line(aes(y = Boundary_Polarisation, color = "Empirical Networks", group = 1)) +  
  
  # Plot points and lines for Random Networks
  geom_point(aes(y = Random_Polarisation, color = "Random Networks"), size = 0.8) +
  geom_line(aes(y = Random_Polarisation, color = "Random Networks", group = 1)) +
  
  # Vertical lines and annotations
  geom_vline(xintercept = 13, linetype = "dashed", color = "black", alpha = 0.5) +
  geom_vline(xintercept = 15, linetype = "dashed", color = "black", alpha = 0.5) +
  annotate("text", x = 13, y = 0.1, label = "Election", vjust = 0, color = "black", family = "Times New Roman", size = 6) +
  annotate("text", x = 15, y = 0.1, label = "Riots", vjust = -2, color = "black", family = "Times New Roman", size = 6) +
  
  # Labels and title
  labs(x = "Month", y = "Spearman's Rho", title = "Figure C3. Boundary Polarisation Scores for Networks with Equal Pages per Party", color = "Network Type") +
  
  # Set custom colors for the lines and points
  scale_color_manual(values = custom_colors) +
  
  # Apply theme settings
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 15, angle = 45, hjust = 1, family = "Times New Roman"),
    axis.text.y = element_text(size = 15, family = "Times New Roman"),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    plot.title = element_text(size = 25, family = "Times New Roman", hjust = 0.5),
    legend.text = element_text(size = 15, family = "Times New Roman"),
    legend.title = element_text(size = 20, family = "Times New Roman")
  ) +
  scale_y_continuous(limits = c(0, NA))
```

```{r robustness_random_walks}
# Create new random networks from networks with "Other" pages
robust_net_sep20_full <- create_net_robust(net_clicksep20)
robust_net_oct20_full <- create_net_robust(net_clickoct20)
robust_net_nov20_full <- create_net_robust(net_clicknov20)
robust_net_dec20_full <- create_net_robust(net_clickdec20)
robust_net_jan21_full <- create_net_robust(net_clickjan21)
robust_net_feb21_full <- create_net_robust(net_clickfeb21)

# Run random walks
results_robust_sep20_dem <- analyze_party_walk(
  robust_net_sep20_full, "Democrat", page_names_democrat_sep, steps = 5, iterations = 50)
results_robust_sep20_rep <- analyze_party_walk(
  robust_net_sep20_full, "Republican", page_names_republican_sep, steps = 5, iterations = 50)

results_robust_oct20_dem <- analyze_party_walk(
  robust_net_oct20_full, "Democrat", page_names_democrat_oct, steps = 5, iterations = 50)
results_robust_oct20_rep <- analyze_party_walk(
  robust_net_oct20_full, "Republican", page_names_republican_oct, steps = 5, iterations = 50)

results_robust_nov20_dem <- analyze_party_walk(
  robust_net_nov20_full, "Democrat", page_names_democrat, steps = 5, iterations = 50)
results_robust_nov20_rep <- analyze_party_walk(
  robust_net_nov20_full, "Republican", page_names_republican, steps = 5, iterations = 50)

results_robust_dec20_dem <- analyze_party_walk(
  robust_net_dec20_full, "Democrat", page_names_democrat_dec, steps = 5, iterations = 50)
results_robust_dec20_rep <- analyze_party_walk(
  robust_net_dec20_full, "Republican", page_names_republican_dec, steps = 5, iterations = 50)

results_robust_jan21_dem <- analyze_party_walk(
  robust_net_jan21_full, "Democrat", page_names_democrat_jan, steps = 5, iterations = 50)
results_robust_jan21_rep <- analyze_party_walk(
  robust_net_jan21_full, "Republican", page_names_republican_jan, steps = 5, iterations = 50)

results_robust_feb21_dem <- analyze_party_walk(
  robust_net_feb21_full, "Democrat", page_names_democrat_feb, steps = 5, iterations = 50)
results_robust_feb21_rep <- analyze_party_walk(robust_net_feb21_full, "Republican", page_names_republican_feb, steps = 5, iterations = 50)

# Calculate exposure to diverse information
exposure_robust_sep20 <- calculate_exposure(results_robust_sep20_dem)
exposure_robust_sep20_rep <- calculate_exposure(results_robust_sep20_rep)

exposure_robust_oct20 <- calculate_exposure(results_robust_oct20_dem)
exposure_robust_oct20_rep <- calculate_exposure(results_robust_oct20_rep)

exposure_robust_nov20 <- calculate_exposure(results_robust_nov20_dem)
exposure_robust_nov20_rep <- calculate_exposure(results_robust_nov20_rep)

exposure_robust_dec20 <- calculate_exposure(results_robust_dec20_dem)
exposure_robust_dec20_rep <- calculate_exposure(results_robust_dec20_rep)

exposure_robust_jan21 <- calculate_exposure(results_robust_jan21_dem)
exposure_robust_jan21_rep <- calculate_exposure(results_robust_jan21_rep)

exposure_robust_feb21 <- calculate_exposure(results_robust_feb21_dem)
exposure_robust_feb21_rep <- calculate_exposure(results_robust_feb21_rep)

# Prepare data for plotting
exposure_robust_data <- data.frame(
  month = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"),
  Democrat = c(exposure_robust_sep20, exposure_robust_oct20, exposure_robust_nov20, exposure_robust_dec20, exposure_robust_jan21, exposure_robust_feb21),
  Republican = c(exposure_robust_sep20_rep, exposure_robust_oct20_rep, exposure_robust_nov20_rep, exposure_robust_dec20_rep, exposure_robust_jan21_rep, exposure_robust_feb21_rep)
)

exposure_robust_data$month <- factor(exposure_robust_data$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

exposure_robust_data_long <- pivot_longer(exposure_robust_data, cols = c(Democrat, Republican), names_to = "variable", values_to = "value")

exposure_robust_data_long$variable <- factor(exposure_robust_data_long$variable, levels = c("Democrat", "Republican"))

custom_colors <- c("Democrat" = "dodgerblue", "Republican" = "red")

# Plot the results
ggplot(exposure_robust_data_long, aes(x = month, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Figure C4. Exposure to Diverse Information by Party for Networks with Equal Pages per Party",
    x = "Month",
    y = "Exposure to Diverse Information",
    fill = "Party"
  ) +
  scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    axis.text.x = element_text(size = 15, hjust = 1),
    axis.text.y = element_text(size = 15),
    plot.title = element_text(size = 23, family = "Times New Roman", hjust = 0.5),
    axis.title.x = element_text(size = 20, family = "Times New Roman"),
    axis.title.y = element_text(size = 20, family = "Times New Roman"),
    legend.text = element_text(size = 15, family = "Times New Roman"),
    legend.title = element_text(size = 20, family = "Times New Roman")
  )
```

```{r robustness_exposure_per_step}
# Calculate the exposure to diverse information per step
exposure_percentages_robust_sep <- list(
  democrat = calculate_exposure_percentage(results_robust_sep20_dem),
  republican = calculate_exposure_percentage(results_robust_sep20_rep)
)

exposure_percentages_robust_oct <- list(
  democrat = calculate_exposure_percentage(results_robust_oct20_dem),
  republican = calculate_exposure_percentage(results_robust_oct20_rep)
)

exposure_percentages_robust_nov <- list(
  democrat = calculate_exposure_percentage(results_robust_nov20_dem),
  republican = calculate_exposure_percentage(results_robust_nov20_rep)
)

exposure_percentages_robust_dec <- list(
  democrat = calculate_exposure_percentage(results_robust_dec20_dem),
  republican = calculate_exposure_percentage(results_robust_dec20_rep)
)

exposure_percentages_robust_jan <- list(
  democrat = calculate_exposure_percentage(results_robust_jan21_dem),
  republican = calculate_exposure_percentage(results_robust_jan21_rep)
)

exposure_percentages_robust_feb <- list(
  democrat = calculate_exposure_percentage(results_robust_feb21_dem),
  republican = calculate_exposure_percentage(results_robust_feb21_rep)
)

# Combine and average the exposure percentages for all months
exposure_df_robust <- bind_rows(
  combine_and_average_steps("September 2020", exposure_percentages_robust_sep$democrat, exposure_percentages_robust_sep$republican),
  combine_and_average_steps("October 2020", exposure_percentages_robust_oct$democrat, exposure_percentages_robust_oct$republican),
  combine_and_average_steps("November 2020", exposure_percentages_robust_nov$democrat, exposure_percentages_robust_nov$republican),
  combine_and_average_steps("December 2020", exposure_percentages_robust_dec$democrat, exposure_percentages_robust_dec$republican),
  combine_and_average_steps("January 2021", exposure_percentages_robust_jan$democrat, exposure_percentages_robust_jan$republican),
  combine_and_average_steps("February 2021", exposure_percentages_robust_feb$democrat, exposure_percentages_robust_feb$republican)
)

exposure_df_robust$month <- factor(exposure_df_robust$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

# Plot the results
ggplot(exposure_df_robust, aes(x = steps, y = exposure, color = month, group = month)) +
  geom_line() +
  geom_point(size = 1) +  # Adjust the size of the points
  labs(
    title = "Figure C5. Exposure to Diverse Information By Number of Steps for Networks with Equal Pages per Party",
    x = "Number of Steps",
    y = "% of Walks Exposed to Other Partition",
    color = "Month"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(hjust = 0.5, size = 22), 
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 15),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 18)
  )
```

```{r rw_random_networks_robust}
# Create full random networks for robustness networks
random_robust_net_sep20_full <- sample_degseq(out.deg = degree(robust_net_sep20_full, mode='out'), in.deg = degree(robust_net_sep20_full, mode='in'), method = "simple")

random_robust_net_oct20_full <- sample_degseq(out.deg = degree(robust_net_oct20_full, mode='out'), in.deg = degree(robust_net_oct20_full, mode='in'), method = "simple")

random_robust_net_nov20_full <- sample_degseq(out.deg = degree(robust_net_nov20_full, mode='out'), in.deg = degree(robust_net_nov20_full, mode='in'), method = "simple")

random_robust_net_dec20_full <- sample_degseq(out.deg = degree(robust_net_dec20_full, mode='out'), in.deg = degree(robust_net_dec20_full, mode='in'), method = "simple")

random_robust_net_jan21_full <- sample_degseq(out.deg = degree(robust_net_jan21_full, mode='out'), in.deg = degree(robust_net_jan21_full, mode='in'), method = "simple")

random_robust_net_feb21_full <- sample_degseq(out.deg = degree(robust_net_feb21_full, mode='out'), in.deg = degree(robust_net_feb21_full, mode='in'), method = "simple")

# Assign party attributes to random networks
assign_attributes_and_calculate_correlation(random_robust_net_sep20_full, robust_net_sep20_full, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_robust_net_oct20_full, robust_net_oct20_full, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_robust_net_nov20_full, robust_net_nov20_full, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_robust_net_dec20_full, robust_net_dec20_full, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_robust_net_jan21_full, robust_net_jan21_full, correlation = FALSE)
assign_attributes_and_calculate_correlation(random_robust_net_feb21_full, robust_net_feb21_full, correlation = FALSE)

# Run random walks
results_random_robust_sep20 <- random_walk_random_networks(random_robust_net_sep20_full)
results_random_robust_sep_dem <- results_random_robust_sep20[1]$democrat
results_random_robust_sep_rep <- results_random_robust_sep20[2]$republican

results_random_robust_oct20 <- random_walk_random_networks(random_robust_net_oct20_full)
results_random_robust_oct_dem <- results_random_robust_oct20[1]$democrat
results_random_robust_oct_rep <- results_random_robust_oct20[2]$republican

results_random_robust_nov20 <- random_walk_random_networks(random_robust_net_nov20_full)
results_random_robust_nov_dem <- results_random_robust_nov20[1]$democrat
results_random_robust_nov_rep <- results_random_robust_nov20[2]$republican

results_random_robust_dec20 <- random_walk_random_networks(random_robust_net_dec20_full)
results_random_robust_dec_dem <- results_random_robust_dec20[1]$democrat
results_random_robust_dec_rep <- results_random_robust_dec20[2]$republican

results_random_robust_jan21 <- random_walk_random_networks(random_robust_net_jan21_full)
results_random_robust_jan_dem <- results_random_robust_jan21[1]$democrat
results_random_robust_jan_rep <- results_random_robust_jan21[2]$republican

results_random_robust_feb21 <- random_walk_random_networks(random_robust_net_feb21_full)
results_random_robust_feb_dem <- results_random_robust_feb21[1]$democrat
results_random_robust_feb_rep <- results_random_robust_feb21[2]$republican

# Calculate exposure to diverse information
exposure_random_robust_sep20 <- calculate_exposure(results_random_robust_sep_dem)
exposure_random_robust_sep20_rep <- calculate_exposure(results_random_robust_sep_rep)

exposure_random_robust_oct20 <- calculate_exposure(results_random_robust_oct_dem)
exposure_random_robust_oct20_rep <- calculate_exposure(results_random_robust_oct_rep)

exposure_random_robust_nov20 <- calculate_exposure(results_random_robust_nov_dem)
exposure_random_robust_nov20_rep <- calculate_exposure(results_random_robust_nov_rep)

exposure_random_robust_dec20 <- calculate_exposure(results_random_robust_dec_dem)
exposure_random_robust_dec20_rep <- calculate_exposure(results_random_robust_dec_rep)

exposure_random_robust_jan21 <- calculate_exposure(results_random_robust_jan_dem)
exposure_random_robust_jan21_rep <- calculate_exposure(results_random_robust_jan_rep)

exposure_random_robust_feb21 <- calculate_exposure(results_random_robust_feb_dem)
exposure_random_robust_feb21_rep <- calculate_exposure(results_random_robust_feb_rep)

exposure_random_robust_data <- data.frame(
  month = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"),
  Democrat = c(exposure_random_robust_sep20, exposure_random_robust_oct20, exposure_random_robust_nov20, exposure_random_robust_dec20, exposure_random_robust_jan21, exposure_random_robust_feb21),
  Republican = c(exposure_random_robust_sep20_rep, exposure_random_robust_oct20_rep, exposure_random_robust_nov20_rep, exposure_random_robust_dec20_rep, exposure_random_robust_jan21_rep, exposure_random_robust_feb21_rep)
)

exposure_random_robust_data$month <- factor(exposure_random_robust_data$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

exposure_random_robust_data_long <- pivot_longer(exposure_random_robust_data, cols = c(Democrat, Republican), names_to = "variable", values_to = "value")

exposure_random_robust_data_long$variable <- factor(exposure_random_robust_data_long$variable, levels = c("Democrat", "Republican"))

custom_colors <- c("Democrat" = "dodgerblue", "Republican" = "red")


ggplot(exposure_random_robust_data_long, aes(x = month, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Figure C6. Exposure to Diverse Information by Party for Networks with Equal Pages per Party",
    x = "Month",
    y = "Exposure to Diverse Information",
    fill = "Party"
  ) +
  scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(size = 18, family = "Times New Roman", hjust = 0.5),
    axis.title.x = element_text(size = 15, family = "Times New Roman"),
    axis.title.y = element_text(size = 15, family = "Times New Roman"),
    legend.text = element_text(size = 15, family = "Times New Roman"),
    legend.title = element_text(size = 15, family = "Times New Roman")
  )

```

```{r robustness_exposure_per_step_random}
# Calculate the exposure to diverse information per step
exposure_percentages_random_robust_sep <- list(
  democrat = calculate_exposure_percentage(results_random_robust_sep_dem),
  republican = calculate_exposure_percentage(results_random_robust_sep_rep)
)

exposure_percentages_random_robust_oct <- list(
  democrat = calculate_exposure_percentage(results_random_robust_oct_dem),
  republican = calculate_exposure_percentage(results_random_robust_oct_rep)
)

exposure_percentages_random_robust_nov <- list(
  democrat = calculate_exposure_percentage(results_random_robust_nov_dem),
  republican = calculate_exposure_percentage(results_random_robust_nov_rep)
)

exposure_percentages_random_robust_dec <- list(
  democrat = calculate_exposure_percentage(results_random_robust_dec_dem),
  republican = calculate_exposure_percentage(results_random_robust_dec_rep)
)

exposure_percentages_random_robust_jan <- list(
  democrat = calculate_exposure_percentage(results_random_robust_jan_dem),
  republican = calculate_exposure_percentage(results_random_robust_jan_rep)
)

exposure_percentages_random_robust_feb <- list(
  democrat = calculate_exposure_percentage(results_random_robust_feb_dem),
  republican = calculate_exposure_percentage(results_random_robust_feb_rep)
)

# Combine and average the exposure percentages for all months
exposure_df_random_robust <- bind_rows(
  combine_and_average_steps("September 2020", exposure_percentages_random_robust_sep$democrat, exposure_percentages_random_robust_sep$republican),
  combine_and_average_steps("October 2020", exposure_percentages_random_robust_oct$democrat, exposure_percentages_random_robust_oct$republican),
  combine_and_average_steps("November 2020", exposure_percentages_random_robust_nov$democrat, exposure_percentages_random_robust_nov$republican),
  combine_and_average_steps("December 2020", exposure_percentages_random_robust_dec$democrat, exposure_percentages_random_robust_dec$republican),
  combine_and_average_steps("January 2021", exposure_percentages_random_robust_jan$democrat, exposure_percentages_random_robust_jan$republican),
  combine_and_average_steps("February 2021", exposure_percentages_random_robust_feb$democrat, exposure_percentages_random_robust_feb$republican)
)

exposure_df_random_robust$month <- factor(exposure_df_random_robust$month, levels = c("September 2020", "October 2020", "November 2020", "December 2020", "January 2021", "February 2021"))

# Plot the results
ggplot(exposure_df_random_robust, aes(x = steps, y = exposure, color = month, group = month)) +
  geom_line() +
  geom_point(size = 1) +  # Adjust the size of the points
  labs(
    title = "Figure C7. Exposure to Diverse Information By Number of Steps for Networks with Equal Pages per Party",
    x = "Number of Steps",
    y = "% of Walks Exposed to Other Partition",
    color = "Month"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(hjust = 0.5, size = 22), 
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 15),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 18)
  )
```


```{r}
save.image("data/robustness_checks.RData")
```

